/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the MeshEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MeshEdge{}

// MeshEdge Single directed edge in the per-Domain mesh-topology projection. Mirrors a SSE peer-delta row one-for-one — a renderer that consumes the live stream and a renderer that polls `GET /v1/domains/{domainId}/mesh/topology` converge on byte-identical state.
type MeshEdge struct {
	// Node from which the WireGuard handshake originates. Pinned against the live Peer aggregate so a stale read never returns an edge for a retired Node.
	SourceNodeId string `json:"source_node_id"`
	// Peer Node the handshake terminates against. Same liveness guarantee as `source_node_id`.
	TargetNodeId string       `json:"target_node_id"`
	Mode         MeshEdgeMode `json:"mode"`
	// Bridge Node currently serving as the relay fallback for this edge. Always populated when `mode` is `relayed`; always `null` when `mode` is `direct`.
	RelayNodeId          string         `json:"relay_node_id"`
	Status               MeshEdgeStatus `json:"status"`
	AdditionalProperties map[string]interface{}
}

type _MeshEdge MeshEdge

// NewMeshEdge instantiates a new MeshEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMeshEdge(sourceNodeId string, targetNodeId string, mode MeshEdgeMode, relayNodeId string, status MeshEdgeStatus) *MeshEdge {
	this := MeshEdge{}
	this.SourceNodeId = sourceNodeId
	this.TargetNodeId = targetNodeId
	this.Mode = mode
	this.RelayNodeId = relayNodeId
	this.Status = status
	return &this
}

// NewMeshEdgeWithDefaults instantiates a new MeshEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMeshEdgeWithDefaults() *MeshEdge {
	this := MeshEdge{}
	return &this
}

// GetSourceNodeId returns the SourceNodeId field value
func (o *MeshEdge) GetSourceNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceNodeId
}

// GetSourceNodeIdOk returns a tuple with the SourceNodeId field value
// and a boolean to check if the value has been set.
func (o *MeshEdge) GetSourceNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceNodeId, true
}

// SetSourceNodeId sets field value
func (o *MeshEdge) SetSourceNodeId(v string) {
	o.SourceNodeId = v
}

// GetTargetNodeId returns the TargetNodeId field value
func (o *MeshEdge) GetTargetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetNodeId
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value
// and a boolean to check if the value has been set.
func (o *MeshEdge) GetTargetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNodeId, true
}

// SetTargetNodeId sets field value
func (o *MeshEdge) SetTargetNodeId(v string) {
	o.TargetNodeId = v
}

// GetMode returns the Mode field value
func (o *MeshEdge) GetMode() MeshEdgeMode {
	if o == nil {
		var ret MeshEdgeMode
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *MeshEdge) GetModeOk() (*MeshEdgeMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *MeshEdge) SetMode(v MeshEdgeMode) {
	o.Mode = v
}

// GetRelayNodeId returns the RelayNodeId field value
func (o *MeshEdge) GetRelayNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RelayNodeId
}

// GetRelayNodeIdOk returns a tuple with the RelayNodeId field value
// and a boolean to check if the value has been set.
func (o *MeshEdge) GetRelayNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RelayNodeId, true
}

// SetRelayNodeId sets field value
func (o *MeshEdge) SetRelayNodeId(v string) {
	o.RelayNodeId = v
}

// GetStatus returns the Status field value
func (o *MeshEdge) GetStatus() MeshEdgeStatus {
	if o == nil {
		var ret MeshEdgeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MeshEdge) GetStatusOk() (*MeshEdgeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MeshEdge) SetStatus(v MeshEdgeStatus) {
	o.Status = v
}

func (o MeshEdge) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MeshEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_node_id"] = o.SourceNodeId
	toSerialize["target_node_id"] = o.TargetNodeId
	toSerialize["mode"] = o.Mode
	toSerialize["relay_node_id"] = o.RelayNodeId
	toSerialize["status"] = o.Status

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MeshEdge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_node_id",
		"target_node_id",
		"mode",
		"relay_node_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMeshEdge := _MeshEdge{}

	err = json.Unmarshal(data, &varMeshEdge)

	if err != nil {
		return err
	}

	*o = MeshEdge(varMeshEdge)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source_node_id")
		delete(additionalProperties, "target_node_id")
		delete(additionalProperties, "mode")
		delete(additionalProperties, "relay_node_id")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMeshEdge struct {
	value *MeshEdge
	isSet bool
}

func (v NullableMeshEdge) Get() *MeshEdge {
	return v.value
}

func (v *NullableMeshEdge) Set(val *MeshEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableMeshEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableMeshEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMeshEdge(val *MeshEdge) *NullableMeshEdge {
	return &NullableMeshEdge{value: val, isSet: true}
}

func (v NullableMeshEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMeshEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
