/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
)

// checks if the ProviderBundlePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBundlePatchRequest{}

// ProviderBundlePatchRequest Body for `PATCH /v1/provider-bundles/{id}`. All properties are optional — but the body MUST set at least one of `display_name`, `provider_packages`, or `provider_config_api_version`. An empty body is rejected at the handler with `400 empty_patch`. A `provider_packages` patch replaces the whole set as one unit: the packages the body names become the bundle's packages and every package it omits is dropped. An empty array, a duplicate `source`, or a package missing one of its two members is rejected with `400 invalid_provider_bundle`.  The immutable `slug` and `provider` are intentionally absent from this schema; the handler rejects a body carrying `slug` with `400 slug_immutable` and one carrying `provider` with `400 provider_immutable`. `provider` is the compatibility key every stored Cloud reference was admitted against, and nothing re-checks a reference once it is stored. See the `PatchProviderBundle` description for the full rationale.
type ProviderBundlePatchRequest struct {
	// New human-readable bundle name. The aggregate's `Rename` mutator validates the same constraints as construction.
	DisplayName *string `json:"display_name,omitempty"`
	// Replacement package set. The whole set is replaced rather than merged. Omit the field to leave the current set untouched. The read surfaces render the result in canonical source-ascending order.
	ProviderPackages []CloudProviderPackage `json:"provider_packages,omitempty"`
	// New `<group>/<version>` every declared package serves its ProviderConfig under. Patchable independently of `provider_packages`: a package bump within one provider family keeps the served group, and a family migration changes the group without touching the pins.
	ProviderConfigApiVersion *string `json:"provider_config_api_version,omitempty" validate:"regexp=^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\\/v[0-9]+((alpha|beta)[0-9]+)?$"`
}

// NewProviderBundlePatchRequest instantiates a new ProviderBundlePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBundlePatchRequest() *ProviderBundlePatchRequest {
	this := ProviderBundlePatchRequest{}
	return &this
}

// NewProviderBundlePatchRequestWithDefaults instantiates a new ProviderBundlePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBundlePatchRequestWithDefaults() *ProviderBundlePatchRequest {
	this := ProviderBundlePatchRequest{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ProviderBundlePatchRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBundlePatchRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ProviderBundlePatchRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ProviderBundlePatchRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetProviderPackages returns the ProviderPackages field value if set, zero value otherwise.
func (o *ProviderBundlePatchRequest) GetProviderPackages() []CloudProviderPackage {
	if o == nil || IsNil(o.ProviderPackages) {
		var ret []CloudProviderPackage
		return ret
	}
	return o.ProviderPackages
}

// GetProviderPackagesOk returns a tuple with the ProviderPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBundlePatchRequest) GetProviderPackagesOk() ([]CloudProviderPackage, bool) {
	if o == nil || IsNil(o.ProviderPackages) {
		return nil, false
	}
	return o.ProviderPackages, true
}

// HasProviderPackages returns a boolean if a field has been set.
func (o *ProviderBundlePatchRequest) HasProviderPackages() bool {
	if o != nil && !IsNil(o.ProviderPackages) {
		return true
	}

	return false
}

// SetProviderPackages gets a reference to the given []CloudProviderPackage and assigns it to the ProviderPackages field.
func (o *ProviderBundlePatchRequest) SetProviderPackages(v []CloudProviderPackage) {
	o.ProviderPackages = v
}

// GetProviderConfigApiVersion returns the ProviderConfigApiVersion field value if set, zero value otherwise.
func (o *ProviderBundlePatchRequest) GetProviderConfigApiVersion() string {
	if o == nil || IsNil(o.ProviderConfigApiVersion) {
		var ret string
		return ret
	}
	return *o.ProviderConfigApiVersion
}

// GetProviderConfigApiVersionOk returns a tuple with the ProviderConfigApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBundlePatchRequest) GetProviderConfigApiVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderConfigApiVersion) {
		return nil, false
	}
	return o.ProviderConfigApiVersion, true
}

// HasProviderConfigApiVersion returns a boolean if a field has been set.
func (o *ProviderBundlePatchRequest) HasProviderConfigApiVersion() bool {
	if o != nil && !IsNil(o.ProviderConfigApiVersion) {
		return true
	}

	return false
}

// SetProviderConfigApiVersion gets a reference to the given string and assigns it to the ProviderConfigApiVersion field.
func (o *ProviderBundlePatchRequest) SetProviderConfigApiVersion(v string) {
	o.ProviderConfigApiVersion = &v
}

func (o ProviderBundlePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBundlePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.ProviderPackages) {
		toSerialize["provider_packages"] = o.ProviderPackages
	}
	if !IsNil(o.ProviderConfigApiVersion) {
		toSerialize["provider_config_api_version"] = o.ProviderConfigApiVersion
	}
	return toSerialize, nil
}

type NullableProviderBundlePatchRequest struct {
	value *ProviderBundlePatchRequest
	isSet bool
}

func (v NullableProviderBundlePatchRequest) Get() *ProviderBundlePatchRequest {
	return v.value
}

func (v *NullableProviderBundlePatchRequest) Set(val *ProviderBundlePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBundlePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBundlePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBundlePatchRequest(val *ProviderBundlePatchRequest) *NullableProviderBundlePatchRequest {
	return &NullableProviderBundlePatchRequest{value: val, isSet: true}
}

func (v NullableProviderBundlePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBundlePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
