/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AuditEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditEvent{}

// AuditEvent A single normalised audit event in a `POST /v1/nodes/{id}/audit` batch. The batch body is newline-delimited JSON (`application/x-ndjson`), one `AuditEvent` object per line. The closed `source` set mirrors the audit sources the README pins (Linux auditd via AF_AUDIT Netlink, or Kubernetes audit-log tailing). Events are tagged server-side with the originating Node's Domain and Project and routed to Grafana Loki with a separate retention class; the wire body never carries an identity subject or email. `source`, `action`, `outcome`, and `timestamp` are required.
type AuditEvent struct {
	Source AuditEventSource `json:"source"`
	// The audited action (e.g. the syscall name or Kubernetes verb). Required and non-empty.
	Action string `json:"action"`
	// The outcome of the audited action (e.g. `success` / `failure`). Required and non-empty.
	Outcome string `json:"outcome"`
	// RFC 3339 timestamp at which the event occurred. Required.
	Timestamp            time.Time `json:"timestamp"`
	AdditionalProperties map[string]interface{}
}

type _AuditEvent AuditEvent

// NewAuditEvent instantiates a new AuditEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditEvent(source AuditEventSource, action string, outcome string, timestamp time.Time) *AuditEvent {
	this := AuditEvent{}
	this.Source = source
	this.Action = action
	this.Outcome = outcome
	this.Timestamp = timestamp
	return &this
}

// NewAuditEventWithDefaults instantiates a new AuditEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditEventWithDefaults() *AuditEvent {
	this := AuditEvent{}
	return &this
}

// GetSource returns the Source field value
func (o *AuditEvent) GetSource() AuditEventSource {
	if o == nil {
		var ret AuditEventSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetSourceOk() (*AuditEventSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AuditEvent) SetSource(v AuditEventSource) {
	o.Source = v
}

// GetAction returns the Action field value
func (o *AuditEvent) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *AuditEvent) SetAction(v string) {
	o.Action = v
}

// GetOutcome returns the Outcome field value
func (o *AuditEvent) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *AuditEvent) SetOutcome(v string) {
	o.Outcome = v
}

// GetTimestamp returns the Timestamp field value
func (o *AuditEvent) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *AuditEvent) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *AuditEvent) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

func (o AuditEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["action"] = o.Action
	toSerialize["outcome"] = o.Outcome
	toSerialize["timestamp"] = o.Timestamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuditEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"action",
		"outcome",
		"timestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuditEvent := _AuditEvent{}

	err = json.Unmarshal(data, &varAuditEvent)

	if err != nil {
		return err
	}

	*o = AuditEvent(varAuditEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "source")
		delete(additionalProperties, "action")
		delete(additionalProperties, "outcome")
		delete(additionalProperties, "timestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuditEvent struct {
	value *AuditEvent
	isSet bool
}

func (v NullableAuditEvent) Get() *AuditEvent {
	return v.value
}

func (v *NullableAuditEvent) Set(val *AuditEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditEvent(val *AuditEvent) *NullableAuditEvent {
	return &NullableAuditEvent{value: val, isSet: true}
}

func (v NullableAuditEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
