/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// BootstrapTokenIssueRequestKind Discriminates the redemption surface — `node` tokens are redeemed at the Node bootstrap endpoint, `bridge` tokens at the Bridge bootstrap endpoint.
type BootstrapTokenIssueRequestKind string

// List of BootstrapTokenIssueRequest_kind
const (
	BOOTSTRAPTOKENISSUEREQUESTKIND_NODE                     BootstrapTokenIssueRequestKind = "node"
	BOOTSTRAPTOKENISSUEREQUESTKIND_BRIDGE                   BootstrapTokenIssueRequestKind = "bridge"
	BOOTSTRAPTOKENISSUEREQUESTKIND_UNKNOWN_DEFAULT_OPEN_API BootstrapTokenIssueRequestKind = "unknown_default_open_api"
)

// All allowed values of BootstrapTokenIssueRequestKind enum
var AllowedBootstrapTokenIssueRequestKindEnumValues = []BootstrapTokenIssueRequestKind{
	"node",
	"bridge",
	"unknown_default_open_api",
}

func (v *BootstrapTokenIssueRequestKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BootstrapTokenIssueRequestKind(value)
	for _, existing := range AllowedBootstrapTokenIssueRequestKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = BOOTSTRAPTOKENISSUEREQUESTKIND_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewBootstrapTokenIssueRequestKindFromValue returns a pointer to a valid BootstrapTokenIssueRequestKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBootstrapTokenIssueRequestKindFromValue(v string) (*BootstrapTokenIssueRequestKind, error) {
	ev := BootstrapTokenIssueRequestKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BootstrapTokenIssueRequestKind: valid values are %v", v, AllowedBootstrapTokenIssueRequestKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BootstrapTokenIssueRequestKind) IsValid() bool {
	for _, existing := range AllowedBootstrapTokenIssueRequestKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BootstrapTokenIssueRequest_kind value
func (v BootstrapTokenIssueRequestKind) Ptr() *BootstrapTokenIssueRequestKind {
	return &v
}

type NullableBootstrapTokenIssueRequestKind struct {
	value *BootstrapTokenIssueRequestKind
	isSet bool
}

func (v NullableBootstrapTokenIssueRequestKind) Get() *BootstrapTokenIssueRequestKind {
	return v.value
}

func (v *NullableBootstrapTokenIssueRequestKind) Set(val *BootstrapTokenIssueRequestKind) {
	v.value = val
	v.isSet = true
}

func (v NullableBootstrapTokenIssueRequestKind) IsSet() bool {
	return v.isSet
}

func (v *NullableBootstrapTokenIssueRequestKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBootstrapTokenIssueRequestKind(val *BootstrapTokenIssueRequestKind) *NullableBootstrapTokenIssueRequestKind {
	return &NullableBootstrapTokenIssueRequestKind{value: val, isSet: true}
}

func (v NullableBootstrapTokenIssueRequestKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBootstrapTokenIssueRequestKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
