/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProjectBlueprintOffer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectBlueprintOffer{}

// ProjectBlueprintOffer A Blueprint Catalog entry seen from inside one Project: the catalogue metadata, the provider kinds its published versions accept, and whether the Project can provision it today.
type ProjectBlueprintOffer struct {
	// Blueprint identifier (UUIDv7).
	Id string `json:"id"`
	// Kebab-case URL handle, unique across the catalogue.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// Human-readable Blueprint name.
	DisplayName string `json:"display_name"`
	// Optional free-form Blueprint description. Absent when the catalogue entry declares none.
	Description *string                 `json:"description,omitempty"`
	Status      BlueprintResponseStatus `json:"status"`
	// Union of the substrates the Blueprint's published versions accept, deduplicated and sorted ascending. Empty when the Blueprint has no published version, which also makes `provisionable` false.
	ProviderKinds []BlueprintVersionCreateRequestProviderKindsInner `json:"provider_kinds"`
	// True when `provider_kinds` intersects the Project's `reachable_provider_kinds`. The verdict is assignment-level: it does not promise an assigned credential for the matching Cloud.
	Provisionable bool `json:"provisionable"`
	// Blueprint creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-modified timestamp (UTC).
	UpdatedAt            time.Time `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _ProjectBlueprintOffer ProjectBlueprintOffer

// NewProjectBlueprintOffer instantiates a new ProjectBlueprintOffer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectBlueprintOffer(id string, slug string, displayName string, status BlueprintResponseStatus, providerKinds []BlueprintVersionCreateRequestProviderKindsInner, provisionable bool, createdAt time.Time, updatedAt time.Time) *ProjectBlueprintOffer {
	this := ProjectBlueprintOffer{}
	this.Id = id
	this.Slug = slug
	this.DisplayName = displayName
	this.Status = status
	this.ProviderKinds = providerKinds
	this.Provisionable = provisionable
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewProjectBlueprintOfferWithDefaults instantiates a new ProjectBlueprintOffer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectBlueprintOfferWithDefaults() *ProjectBlueprintOffer {
	this := ProjectBlueprintOffer{}
	return &this
}

// GetId returns the Id field value
func (o *ProjectBlueprintOffer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectBlueprintOffer) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *ProjectBlueprintOffer) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ProjectBlueprintOffer) SetSlug(v string) {
	o.Slug = v
}

// GetDisplayName returns the DisplayName field value
func (o *ProjectBlueprintOffer) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ProjectBlueprintOffer) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProjectBlueprintOffer) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProjectBlueprintOffer) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProjectBlueprintOffer) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value
func (o *ProjectBlueprintOffer) GetStatus() BlueprintResponseStatus {
	if o == nil {
		var ret BlueprintResponseStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetStatusOk() (*BlueprintResponseStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectBlueprintOffer) SetStatus(v BlueprintResponseStatus) {
	o.Status = v
}

// GetProviderKinds returns the ProviderKinds field value
func (o *ProjectBlueprintOffer) GetProviderKinds() []BlueprintVersionCreateRequestProviderKindsInner {
	if o == nil {
		var ret []BlueprintVersionCreateRequestProviderKindsInner
		return ret
	}

	return o.ProviderKinds
}

// GetProviderKindsOk returns a tuple with the ProviderKinds field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetProviderKindsOk() ([]BlueprintVersionCreateRequestProviderKindsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderKinds, true
}

// SetProviderKinds sets field value
func (o *ProjectBlueprintOffer) SetProviderKinds(v []BlueprintVersionCreateRequestProviderKindsInner) {
	o.ProviderKinds = v
}

// GetProvisionable returns the Provisionable field value
func (o *ProjectBlueprintOffer) GetProvisionable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Provisionable
}

// GetProvisionableOk returns a tuple with the Provisionable field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetProvisionableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provisionable, true
}

// SetProvisionable sets field value
func (o *ProjectBlueprintOffer) SetProvisionable(v bool) {
	o.Provisionable = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProjectBlueprintOffer) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProjectBlueprintOffer) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ProjectBlueprintOffer) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ProjectBlueprintOffer) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ProjectBlueprintOffer) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ProjectBlueprintOffer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectBlueprintOffer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["display_name"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["status"] = o.Status
	toSerialize["provider_kinds"] = o.ProviderKinds
	toSerialize["provisionable"] = o.Provisionable
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProjectBlueprintOffer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"display_name",
		"status",
		"provider_kinds",
		"provisionable",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectBlueprintOffer := _ProjectBlueprintOffer{}

	err = json.Unmarshal(data, &varProjectBlueprintOffer)

	if err != nil {
		return err
	}

	*o = ProjectBlueprintOffer(varProjectBlueprintOffer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		delete(additionalProperties, "provider_kinds")
		delete(additionalProperties, "provisionable")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProjectBlueprintOffer struct {
	value *ProjectBlueprintOffer
	isSet bool
}

func (v NullableProjectBlueprintOffer) Get() *ProjectBlueprintOffer {
	return v.value
}

func (v *NullableProjectBlueprintOffer) Set(val *ProjectBlueprintOffer) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectBlueprintOffer) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectBlueprintOffer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectBlueprintOffer(val *ProjectBlueprintOffer) *NullableProjectBlueprintOffer {
	return &NullableProjectBlueprintOffer{value: val, isSet: true}
}

func (v NullableProjectBlueprintOffer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectBlueprintOffer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
