/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the ImportOutcome type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportOutcome{}

// ImportOutcome One Blueprint's import result. `version` carries the metadata version label for the `imported`, `unchanged`, and `drift` statuses; `detail` carries the drift diff for `drift`; `reason` carries a machine-readable code for the `conflict` and `error` statuses.
type ImportOutcome struct {
	// The Blueprint slug this outcome reports on.
	Slug   string              `json:"slug"`
	Status ImportOutcomeStatus `json:"status"`
	// The version label, present for `imported`, `unchanged`, and `drift`.
	Version *string `json:"version,omitempty"`
	// The drift diff, present for the `drift` status.
	Detail               *string              `json:"detail,omitempty"`
	Reason               *ImportOutcomeReason `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ImportOutcome ImportOutcome

// NewImportOutcome instantiates a new ImportOutcome object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportOutcome(slug string, status ImportOutcomeStatus) *ImportOutcome {
	this := ImportOutcome{}
	this.Slug = slug
	this.Status = status
	return &this
}

// NewImportOutcomeWithDefaults instantiates a new ImportOutcome object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportOutcomeWithDefaults() *ImportOutcome {
	this := ImportOutcome{}
	return &this
}

// GetSlug returns the Slug field value
func (o *ImportOutcome) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ImportOutcome) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ImportOutcome) SetSlug(v string) {
	o.Slug = v
}

// GetStatus returns the Status field value
func (o *ImportOutcome) GetStatus() ImportOutcomeStatus {
	if o == nil {
		var ret ImportOutcomeStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ImportOutcome) GetStatusOk() (*ImportOutcomeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ImportOutcome) SetStatus(v ImportOutcomeStatus) {
	o.Status = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ImportOutcome) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOutcome) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ImportOutcome) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ImportOutcome) SetVersion(v string) {
	o.Version = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ImportOutcome) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOutcome) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ImportOutcome) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ImportOutcome) SetDetail(v string) {
	o.Detail = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ImportOutcome) GetReason() ImportOutcomeReason {
	if o == nil || IsNil(o.Reason) {
		var ret ImportOutcomeReason
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOutcome) GetReasonOk() (*ImportOutcomeReason, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ImportOutcome) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given ImportOutcomeReason and assigns it to the Reason field.
func (o *ImportOutcome) SetReason(v ImportOutcomeReason) {
	o.Reason = &v
}

func (o ImportOutcome) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportOutcome) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["status"] = o.Status
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImportOutcome) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImportOutcome := _ImportOutcome{}

	err = json.Unmarshal(data, &varImportOutcome)

	if err != nil {
		return err
	}

	*o = ImportOutcome(varImportOutcome)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slug")
		delete(additionalProperties, "status")
		delete(additionalProperties, "version")
		delete(additionalProperties, "detail")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImportOutcome struct {
	value *ImportOutcome
	isSet bool
}

func (v NullableImportOutcome) Get() *ImportOutcome {
	return v.value
}

func (v *NullableImportOutcome) Set(val *ImportOutcome) {
	v.value = val
	v.isSet = true
}

func (v NullableImportOutcome) IsSet() bool {
	return v.isSet
}

func (v *NullableImportOutcome) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportOutcome(val *ImportOutcome) *NullableImportOutcome {
	return &NullableImportOutcome{value: val, isSet: true}
}

func (v NullableImportOutcome) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportOutcome) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
