/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the LabelDefinitionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelDefinitionRequest{}

// LabelDefinitionRequest Body for POST /v1/label-definitions. Mirrors the DDD `CreateDefinitionParams` shape: the caller names the scope as a discriminator + optional UUID, the local key, and the value contract. The services layer performs the `manage` ReBAC check on the scope-object before persisting.
type LabelDefinitionRequest struct {
	Scope LabelDefinitionRequestScope `json:"scope"`
	// Tenancy identifier. Required when `scope` is `domain` or `project`; omitted when `scope=platform`.
	ScopeId *string `json:"scope_id,omitempty"`
	// Unqualified key token — lowercase letters, digits, `.`, `_`, `-`; 1–64 characters; no leading or trailing separator.
	LocalKey        string           `json:"local_key"`
	Description     *string          `json:"description,omitempty"`
	ValueSchema     LabelValueSchema `json:"value_schema"`
	ApplicableKinds []string         `json:"applicable_kinds"`
	// When `true`, Assignments of this Definition are mandatory on every object of the applicable kinds.
	Required            *bool                           `json:"required,omitempty"`
	DefaultValue        interface{}                     `json:"default_value,omitempty"`
	Immutable           *bool                           `json:"immutable,omitempty"`
	CloudTagPropagation *bool                           `json:"cloud_tag_propagation,omitempty"`
	OnDelete            *LabelDefinitionRequestOnDelete `json:"on_delete,omitempty"`
	// Declared per-object cardinality cap for Assignments of this Definition. Defaults to `1` when omitted .
	Cardinality          *int32 `json:"cardinality,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelDefinitionRequest LabelDefinitionRequest

// NewLabelDefinitionRequest instantiates a new LabelDefinitionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelDefinitionRequest(scope LabelDefinitionRequestScope, localKey string, valueSchema LabelValueSchema, applicableKinds []string) *LabelDefinitionRequest {
	this := LabelDefinitionRequest{}
	this.Scope = scope
	this.LocalKey = localKey
	this.ValueSchema = valueSchema
	this.ApplicableKinds = applicableKinds
	return &this
}

// NewLabelDefinitionRequestWithDefaults instantiates a new LabelDefinitionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelDefinitionRequestWithDefaults() *LabelDefinitionRequest {
	this := LabelDefinitionRequest{}
	return &this
}

// GetScope returns the Scope field value
func (o *LabelDefinitionRequest) GetScope() LabelDefinitionRequestScope {
	if o == nil {
		var ret LabelDefinitionRequestScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetScopeOk() (*LabelDefinitionRequestScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *LabelDefinitionRequest) SetScope(v LabelDefinitionRequestScope) {
	o.Scope = v
}

// GetScopeId returns the ScopeId field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetScopeId() string {
	if o == nil || IsNil(o.ScopeId) {
		var ret string
		return ret
	}
	return *o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetScopeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScopeId) {
		return nil, false
	}
	return o.ScopeId, true
}

// HasScopeId returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasScopeId() bool {
	if o != nil && !IsNil(o.ScopeId) {
		return true
	}

	return false
}

// SetScopeId gets a reference to the given string and assigns it to the ScopeId field.
func (o *LabelDefinitionRequest) SetScopeId(v string) {
	o.ScopeId = &v
}

// GetLocalKey returns the LocalKey field value
func (o *LabelDefinitionRequest) GetLocalKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocalKey
}

// GetLocalKeyOk returns a tuple with the LocalKey field value
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetLocalKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocalKey, true
}

// SetLocalKey sets field value
func (o *LabelDefinitionRequest) SetLocalKey(v string) {
	o.LocalKey = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LabelDefinitionRequest) SetDescription(v string) {
	o.Description = &v
}

// GetValueSchema returns the ValueSchema field value
func (o *LabelDefinitionRequest) GetValueSchema() LabelValueSchema {
	if o == nil {
		var ret LabelValueSchema
		return ret
	}

	return o.ValueSchema
}

// GetValueSchemaOk returns a tuple with the ValueSchema field value
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetValueSchemaOk() (*LabelValueSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueSchema, true
}

// SetValueSchema sets field value
func (o *LabelDefinitionRequest) SetValueSchema(v LabelValueSchema) {
	o.ValueSchema = v
}

// GetApplicableKinds returns the ApplicableKinds field value
func (o *LabelDefinitionRequest) GetApplicableKinds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApplicableKinds
}

// GetApplicableKindsOk returns a tuple with the ApplicableKinds field value
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetApplicableKindsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicableKinds, true
}

// SetApplicableKinds sets field value
func (o *LabelDefinitionRequest) SetApplicableKinds(v []string) {
	o.ApplicableKinds = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *LabelDefinitionRequest) SetRequired(v bool) {
	o.Required = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LabelDefinitionRequest) GetDefaultValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LabelDefinitionRequest) GetDefaultValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DefaultValue) {
		return nil, false
	}
	return &o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasDefaultValue() bool {
	if o != nil && !IsNil(o.DefaultValue) {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given interface{} and assigns it to the DefaultValue field.
func (o *LabelDefinitionRequest) SetDefaultValue(v interface{}) {
	o.DefaultValue = v
}

// GetImmutable returns the Immutable field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetImmutable() bool {
	if o == nil || IsNil(o.Immutable) {
		var ret bool
		return ret
	}
	return *o.Immutable
}

// GetImmutableOk returns a tuple with the Immutable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetImmutableOk() (*bool, bool) {
	if o == nil || IsNil(o.Immutable) {
		return nil, false
	}
	return o.Immutable, true
}

// HasImmutable returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasImmutable() bool {
	if o != nil && !IsNil(o.Immutable) {
		return true
	}

	return false
}

// SetImmutable gets a reference to the given bool and assigns it to the Immutable field.
func (o *LabelDefinitionRequest) SetImmutable(v bool) {
	o.Immutable = &v
}

// GetCloudTagPropagation returns the CloudTagPropagation field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetCloudTagPropagation() bool {
	if o == nil || IsNil(o.CloudTagPropagation) {
		var ret bool
		return ret
	}
	return *o.CloudTagPropagation
}

// GetCloudTagPropagationOk returns a tuple with the CloudTagPropagation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetCloudTagPropagationOk() (*bool, bool) {
	if o == nil || IsNil(o.CloudTagPropagation) {
		return nil, false
	}
	return o.CloudTagPropagation, true
}

// HasCloudTagPropagation returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasCloudTagPropagation() bool {
	if o != nil && !IsNil(o.CloudTagPropagation) {
		return true
	}

	return false
}

// SetCloudTagPropagation gets a reference to the given bool and assigns it to the CloudTagPropagation field.
func (o *LabelDefinitionRequest) SetCloudTagPropagation(v bool) {
	o.CloudTagPropagation = &v
}

// GetOnDelete returns the OnDelete field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetOnDelete() LabelDefinitionRequestOnDelete {
	if o == nil || IsNil(o.OnDelete) {
		var ret LabelDefinitionRequestOnDelete
		return ret
	}
	return *o.OnDelete
}

// GetOnDeleteOk returns a tuple with the OnDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetOnDeleteOk() (*LabelDefinitionRequestOnDelete, bool) {
	if o == nil || IsNil(o.OnDelete) {
		return nil, false
	}
	return o.OnDelete, true
}

// HasOnDelete returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasOnDelete() bool {
	if o != nil && !IsNil(o.OnDelete) {
		return true
	}

	return false
}

// SetOnDelete gets a reference to the given LabelDefinitionRequestOnDelete and assigns it to the OnDelete field.
func (o *LabelDefinitionRequest) SetOnDelete(v LabelDefinitionRequestOnDelete) {
	o.OnDelete = &v
}

// GetCardinality returns the Cardinality field value if set, zero value otherwise.
func (o *LabelDefinitionRequest) GetCardinality() int32 {
	if o == nil || IsNil(o.Cardinality) {
		var ret int32
		return ret
	}
	return *o.Cardinality
}

// GetCardinalityOk returns a tuple with the Cardinality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelDefinitionRequest) GetCardinalityOk() (*int32, bool) {
	if o == nil || IsNil(o.Cardinality) {
		return nil, false
	}
	return o.Cardinality, true
}

// HasCardinality returns a boolean if a field has been set.
func (o *LabelDefinitionRequest) HasCardinality() bool {
	if o != nil && !IsNil(o.Cardinality) {
		return true
	}

	return false
}

// SetCardinality gets a reference to the given int32 and assigns it to the Cardinality field.
func (o *LabelDefinitionRequest) SetCardinality(v int32) {
	o.Cardinality = &v
}

func (o LabelDefinitionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelDefinitionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	if !IsNil(o.ScopeId) {
		toSerialize["scope_id"] = o.ScopeId
	}
	toSerialize["local_key"] = o.LocalKey
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["value_schema"] = o.ValueSchema
	toSerialize["applicable_kinds"] = o.ApplicableKinds
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if o.DefaultValue != nil {
		toSerialize["default_value"] = o.DefaultValue
	}
	if !IsNil(o.Immutable) {
		toSerialize["immutable"] = o.Immutable
	}
	if !IsNil(o.CloudTagPropagation) {
		toSerialize["cloud_tag_propagation"] = o.CloudTagPropagation
	}
	if !IsNil(o.OnDelete) {
		toSerialize["on_delete"] = o.OnDelete
	}
	if !IsNil(o.Cardinality) {
		toSerialize["cardinality"] = o.Cardinality
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelDefinitionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
		"local_key",
		"value_schema",
		"applicable_kinds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabelDefinitionRequest := _LabelDefinitionRequest{}

	err = json.Unmarshal(data, &varLabelDefinitionRequest)

	if err != nil {
		return err
	}

	*o = LabelDefinitionRequest(varLabelDefinitionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "scope")
		delete(additionalProperties, "scope_id")
		delete(additionalProperties, "local_key")
		delete(additionalProperties, "description")
		delete(additionalProperties, "value_schema")
		delete(additionalProperties, "applicable_kinds")
		delete(additionalProperties, "required")
		delete(additionalProperties, "default_value")
		delete(additionalProperties, "immutable")
		delete(additionalProperties, "cloud_tag_propagation")
		delete(additionalProperties, "on_delete")
		delete(additionalProperties, "cardinality")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLabelDefinitionRequest struct {
	value *LabelDefinitionRequest
	isSet bool
}

func (v NullableLabelDefinitionRequest) Get() *LabelDefinitionRequest {
	return v.value
}

func (v *NullableLabelDefinitionRequest) Set(val *LabelDefinitionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelDefinitionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelDefinitionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelDefinitionRequest(val *LabelDefinitionRequest) *NullableLabelDefinitionRequest {
	return &NullableLabelDefinitionRequest{value: val, isSet: true}
}

func (v NullableLabelDefinitionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelDefinitionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
