/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the SessionActivityTCP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionActivityTCP{}

// SessionActivityTCP TCP session lifecycle activity a Node posts for a `tcp` session. The shape is deliberately payload-blind — exactly a start and an end with byte counters, no L7 interpretation.
type SessionActivityTCP struct {
	Phase SessionActivityTCPPhase `json:"phase"`
	// Target host the tunnel connected to. Present on `session_started`.
	TargetHost *string `json:"target_host,omitempty"`
	// Target port the tunnel connected to. Present on `session_started`.
	TargetPort *int32 `json:"target_port,omitempty"`
	// Bytes forwarded from the operator to the target. Present on `session_ended`.
	BytesIn *int32 `json:"bytes_in,omitempty"`
	// Bytes forwarded from the target to the operator. Present on `session_ended`.
	BytesOut             *int32                          `json:"bytes_out,omitempty"`
	TerminatedBy         *SessionActivityTCPTerminatedBy `json:"terminated_by,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SessionActivityTCP SessionActivityTCP

// NewSessionActivityTCP instantiates a new SessionActivityTCP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionActivityTCP(phase SessionActivityTCPPhase) *SessionActivityTCP {
	this := SessionActivityTCP{}
	this.Phase = phase
	return &this
}

// NewSessionActivityTCPWithDefaults instantiates a new SessionActivityTCP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionActivityTCPWithDefaults() *SessionActivityTCP {
	this := SessionActivityTCP{}
	return &this
}

// GetPhase returns the Phase field value
func (o *SessionActivityTCP) GetPhase() SessionActivityTCPPhase {
	if o == nil {
		var ret SessionActivityTCPPhase
		return ret
	}

	return o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetPhaseOk() (*SessionActivityTCPPhase, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase, true
}

// SetPhase sets field value
func (o *SessionActivityTCP) SetPhase(v SessionActivityTCPPhase) {
	o.Phase = v
}

// GetTargetHost returns the TargetHost field value if set, zero value otherwise.
func (o *SessionActivityTCP) GetTargetHost() string {
	if o == nil || IsNil(o.TargetHost) {
		var ret string
		return ret
	}
	return *o.TargetHost
}

// GetTargetHostOk returns a tuple with the TargetHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetTargetHostOk() (*string, bool) {
	if o == nil || IsNil(o.TargetHost) {
		return nil, false
	}
	return o.TargetHost, true
}

// HasTargetHost returns a boolean if a field has been set.
func (o *SessionActivityTCP) HasTargetHost() bool {
	if o != nil && !IsNil(o.TargetHost) {
		return true
	}

	return false
}

// SetTargetHost gets a reference to the given string and assigns it to the TargetHost field.
func (o *SessionActivityTCP) SetTargetHost(v string) {
	o.TargetHost = &v
}

// GetTargetPort returns the TargetPort field value if set, zero value otherwise.
func (o *SessionActivityTCP) GetTargetPort() int32 {
	if o == nil || IsNil(o.TargetPort) {
		var ret int32
		return ret
	}
	return *o.TargetPort
}

// GetTargetPortOk returns a tuple with the TargetPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetTargetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetPort) {
		return nil, false
	}
	return o.TargetPort, true
}

// HasTargetPort returns a boolean if a field has been set.
func (o *SessionActivityTCP) HasTargetPort() bool {
	if o != nil && !IsNil(o.TargetPort) {
		return true
	}

	return false
}

// SetTargetPort gets a reference to the given int32 and assigns it to the TargetPort field.
func (o *SessionActivityTCP) SetTargetPort(v int32) {
	o.TargetPort = &v
}

// GetBytesIn returns the BytesIn field value if set, zero value otherwise.
func (o *SessionActivityTCP) GetBytesIn() int32 {
	if o == nil || IsNil(o.BytesIn) {
		var ret int32
		return ret
	}
	return *o.BytesIn
}

// GetBytesInOk returns a tuple with the BytesIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetBytesInOk() (*int32, bool) {
	if o == nil || IsNil(o.BytesIn) {
		return nil, false
	}
	return o.BytesIn, true
}

// HasBytesIn returns a boolean if a field has been set.
func (o *SessionActivityTCP) HasBytesIn() bool {
	if o != nil && !IsNil(o.BytesIn) {
		return true
	}

	return false
}

// SetBytesIn gets a reference to the given int32 and assigns it to the BytesIn field.
func (o *SessionActivityTCP) SetBytesIn(v int32) {
	o.BytesIn = &v
}

// GetBytesOut returns the BytesOut field value if set, zero value otherwise.
func (o *SessionActivityTCP) GetBytesOut() int32 {
	if o == nil || IsNil(o.BytesOut) {
		var ret int32
		return ret
	}
	return *o.BytesOut
}

// GetBytesOutOk returns a tuple with the BytesOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetBytesOutOk() (*int32, bool) {
	if o == nil || IsNil(o.BytesOut) {
		return nil, false
	}
	return o.BytesOut, true
}

// HasBytesOut returns a boolean if a field has been set.
func (o *SessionActivityTCP) HasBytesOut() bool {
	if o != nil && !IsNil(o.BytesOut) {
		return true
	}

	return false
}

// SetBytesOut gets a reference to the given int32 and assigns it to the BytesOut field.
func (o *SessionActivityTCP) SetBytesOut(v int32) {
	o.BytesOut = &v
}

// GetTerminatedBy returns the TerminatedBy field value if set, zero value otherwise.
func (o *SessionActivityTCP) GetTerminatedBy() SessionActivityTCPTerminatedBy {
	if o == nil || IsNil(o.TerminatedBy) {
		var ret SessionActivityTCPTerminatedBy
		return ret
	}
	return *o.TerminatedBy
}

// GetTerminatedByOk returns a tuple with the TerminatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivityTCP) GetTerminatedByOk() (*SessionActivityTCPTerminatedBy, bool) {
	if o == nil || IsNil(o.TerminatedBy) {
		return nil, false
	}
	return o.TerminatedBy, true
}

// HasTerminatedBy returns a boolean if a field has been set.
func (o *SessionActivityTCP) HasTerminatedBy() bool {
	if o != nil && !IsNil(o.TerminatedBy) {
		return true
	}

	return false
}

// SetTerminatedBy gets a reference to the given SessionActivityTCPTerminatedBy and assigns it to the TerminatedBy field.
func (o *SessionActivityTCP) SetTerminatedBy(v SessionActivityTCPTerminatedBy) {
	o.TerminatedBy = &v
}

func (o SessionActivityTCP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionActivityTCP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phase"] = o.Phase
	if !IsNil(o.TargetHost) {
		toSerialize["target_host"] = o.TargetHost
	}
	if !IsNil(o.TargetPort) {
		toSerialize["target_port"] = o.TargetPort
	}
	if !IsNil(o.BytesIn) {
		toSerialize["bytes_in"] = o.BytesIn
	}
	if !IsNil(o.BytesOut) {
		toSerialize["bytes_out"] = o.BytesOut
	}
	if !IsNil(o.TerminatedBy) {
		toSerialize["terminated_by"] = o.TerminatedBy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SessionActivityTCP) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phase",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionActivityTCP := _SessionActivityTCP{}

	err = json.Unmarshal(data, &varSessionActivityTCP)

	if err != nil {
		return err
	}

	*o = SessionActivityTCP(varSessionActivityTCP)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "phase")
		delete(additionalProperties, "target_host")
		delete(additionalProperties, "target_port")
		delete(additionalProperties, "bytes_in")
		delete(additionalProperties, "bytes_out")
		delete(additionalProperties, "terminated_by")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSessionActivityTCP struct {
	value *SessionActivityTCP
	isSet bool
}

func (v NullableSessionActivityTCP) Get() *SessionActivityTCP {
	return v.value
}

func (v *NullableSessionActivityTCP) Set(val *SessionActivityTCP) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionActivityTCP) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionActivityTCP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionActivityTCP(val *SessionActivityTCP) *NullableSessionActivityTCP {
	return &NullableSessionActivityTCP{value: val, isSet: true}
}

func (v NullableSessionActivityTCP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionActivityTCP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
