/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the NodeStateBridgeRelayAssignment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeStateBridgeRelayAssignment{}

// NodeStateBridgeRelayAssignment One per-peer relay fallback assignment: the peer the Node may relay for and the fallback endpoint that peer dials. Population lands with the effective-config story; an empty `assignments` list is the interim state.
type NodeStateBridgeRelayAssignment struct {
	// Peer Node the relay fallback applies to.
	PeerNodeId string `json:"peer_node_id"`
	// Host the peer dials when direct connectivity is unavailable.
	FallbackEndpoint string `json:"fallback_endpoint"`
	// Port on the fallback endpoint the peer dials.
	FallbackEndpointPort int32 `json:"fallback_endpoint_port"`
	AdditionalProperties map[string]interface{}
}

type _NodeStateBridgeRelayAssignment NodeStateBridgeRelayAssignment

// NewNodeStateBridgeRelayAssignment instantiates a new NodeStateBridgeRelayAssignment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeStateBridgeRelayAssignment(peerNodeId string, fallbackEndpoint string, fallbackEndpointPort int32) *NodeStateBridgeRelayAssignment {
	this := NodeStateBridgeRelayAssignment{}
	this.PeerNodeId = peerNodeId
	this.FallbackEndpoint = fallbackEndpoint
	this.FallbackEndpointPort = fallbackEndpointPort
	return &this
}

// NewNodeStateBridgeRelayAssignmentWithDefaults instantiates a new NodeStateBridgeRelayAssignment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeStateBridgeRelayAssignmentWithDefaults() *NodeStateBridgeRelayAssignment {
	this := NodeStateBridgeRelayAssignment{}
	return &this
}

// GetPeerNodeId returns the PeerNodeId field value
func (o *NodeStateBridgeRelayAssignment) GetPeerNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeerNodeId
}

// GetPeerNodeIdOk returns a tuple with the PeerNodeId field value
// and a boolean to check if the value has been set.
func (o *NodeStateBridgeRelayAssignment) GetPeerNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeerNodeId, true
}

// SetPeerNodeId sets field value
func (o *NodeStateBridgeRelayAssignment) SetPeerNodeId(v string) {
	o.PeerNodeId = v
}

// GetFallbackEndpoint returns the FallbackEndpoint field value
func (o *NodeStateBridgeRelayAssignment) GetFallbackEndpoint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FallbackEndpoint
}

// GetFallbackEndpointOk returns a tuple with the FallbackEndpoint field value
// and a boolean to check if the value has been set.
func (o *NodeStateBridgeRelayAssignment) GetFallbackEndpointOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackEndpoint, true
}

// SetFallbackEndpoint sets field value
func (o *NodeStateBridgeRelayAssignment) SetFallbackEndpoint(v string) {
	o.FallbackEndpoint = v
}

// GetFallbackEndpointPort returns the FallbackEndpointPort field value
func (o *NodeStateBridgeRelayAssignment) GetFallbackEndpointPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FallbackEndpointPort
}

// GetFallbackEndpointPortOk returns a tuple with the FallbackEndpointPort field value
// and a boolean to check if the value has been set.
func (o *NodeStateBridgeRelayAssignment) GetFallbackEndpointPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FallbackEndpointPort, true
}

// SetFallbackEndpointPort sets field value
func (o *NodeStateBridgeRelayAssignment) SetFallbackEndpointPort(v int32) {
	o.FallbackEndpointPort = v
}

func (o NodeStateBridgeRelayAssignment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeStateBridgeRelayAssignment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["peer_node_id"] = o.PeerNodeId
	toSerialize["fallback_endpoint"] = o.FallbackEndpoint
	toSerialize["fallback_endpoint_port"] = o.FallbackEndpointPort

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodeStateBridgeRelayAssignment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"peer_node_id",
		"fallback_endpoint",
		"fallback_endpoint_port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeStateBridgeRelayAssignment := _NodeStateBridgeRelayAssignment{}

	err = json.Unmarshal(data, &varNodeStateBridgeRelayAssignment)

	if err != nil {
		return err
	}

	*o = NodeStateBridgeRelayAssignment(varNodeStateBridgeRelayAssignment)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "peer_node_id")
		delete(additionalProperties, "fallback_endpoint")
		delete(additionalProperties, "fallback_endpoint_port")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodeStateBridgeRelayAssignment struct {
	value *NodeStateBridgeRelayAssignment
	isSet bool
}

func (v NullableNodeStateBridgeRelayAssignment) Get() *NodeStateBridgeRelayAssignment {
	return v.value
}

func (v *NullableNodeStateBridgeRelayAssignment) Set(val *NodeStateBridgeRelayAssignment) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeStateBridgeRelayAssignment) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeStateBridgeRelayAssignment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeStateBridgeRelayAssignment(val *NodeStateBridgeRelayAssignment) *NullableNodeStateBridgeRelayAssignment {
	return &NullableNodeStateBridgeRelayAssignment{value: val, isSet: true}
}

func (v NullableNodeStateBridgeRelayAssignment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeStateBridgeRelayAssignment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
