/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// ServiceTokenRequestGrantType OAuth2 grant type used to authenticate the service.
type ServiceTokenRequestGrantType string

// List of ServiceTokenRequest_grant_type
const (
	SERVICETOKENREQUESTGRANTTYPE_CLIENT_CREDENTIALS                          ServiceTokenRequestGrantType = "client_credentials"
	SERVICETOKENREQUESTGRANTTYPE_URN_IETF_PARAMS_OAUTH_GRANT_TYPE_JWT_BEARER ServiceTokenRequestGrantType = "urn:ietf:params:oauth:grant-type:jwt-bearer"
	SERVICETOKENREQUESTGRANTTYPE_UNKNOWN_DEFAULT_OPEN_API                    ServiceTokenRequestGrantType = "unknown_default_open_api"
)

// All allowed values of ServiceTokenRequestGrantType enum
var AllowedServiceTokenRequestGrantTypeEnumValues = []ServiceTokenRequestGrantType{
	"client_credentials",
	"urn:ietf:params:oauth:grant-type:jwt-bearer",
	"unknown_default_open_api",
}

func (v *ServiceTokenRequestGrantType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServiceTokenRequestGrantType(value)
	for _, existing := range AllowedServiceTokenRequestGrantTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SERVICETOKENREQUESTGRANTTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewServiceTokenRequestGrantTypeFromValue returns a pointer to a valid ServiceTokenRequestGrantType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServiceTokenRequestGrantTypeFromValue(v string) (*ServiceTokenRequestGrantType, error) {
	ev := ServiceTokenRequestGrantType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServiceTokenRequestGrantType: valid values are %v", v, AllowedServiceTokenRequestGrantTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServiceTokenRequestGrantType) IsValid() bool {
	for _, existing := range AllowedServiceTokenRequestGrantTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServiceTokenRequest_grant_type value
func (v ServiceTokenRequestGrantType) Ptr() *ServiceTokenRequestGrantType {
	return &v
}

type NullableServiceTokenRequestGrantType struct {
	value *ServiceTokenRequestGrantType
	isSet bool
}

func (v NullableServiceTokenRequestGrantType) Get() *ServiceTokenRequestGrantType {
	return v.value
}

func (v *NullableServiceTokenRequestGrantType) Set(val *ServiceTokenRequestGrantType) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceTokenRequestGrantType) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceTokenRequestGrantType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceTokenRequestGrantType(val *ServiceTokenRequestGrantType) *NullableServiceTokenRequestGrantType {
	return &NullableServiceTokenRequestGrantType{value: val, isSet: true}
}

func (v NullableServiceTokenRequestGrantType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceTokenRequestGrantType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
