/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// SinkType Protocol or backend one sink delivers to. `otlp` and `syslog` are the forwarding protocols a Domain declares for itself; `mimir`, `loki` and `siem` name the platform's own backends and appear on built-in sinks only.
type SinkType string

// List of SinkType
const (
	SINKTYPE_OTLP                     SinkType = "otlp"
	SINKTYPE_SYSLOG                   SinkType = "syslog"
	SINKTYPE_MIMIR                    SinkType = "mimir"
	SINKTYPE_LOKI                     SinkType = "loki"
	SINKTYPE_SIEM                     SinkType = "siem"
	SINKTYPE_UNKNOWN_DEFAULT_OPEN_API SinkType = "unknown_default_open_api"
)

// All allowed values of SinkType enum
var AllowedSinkTypeEnumValues = []SinkType{
	"otlp",
	"syslog",
	"mimir",
	"loki",
	"siem",
	"unknown_default_open_api",
}

func (v *SinkType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SinkType(value)
	for _, existing := range AllowedSinkTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SINKTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewSinkTypeFromValue returns a pointer to a valid SinkType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSinkTypeFromValue(v string) (*SinkType, error) {
	ev := SinkType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SinkType: valid values are %v", v, AllowedSinkTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SinkType) IsValid() bool {
	for _, existing := range AllowedSinkTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SinkType value
func (v SinkType) Ptr() *SinkType {
	return &v
}

type NullableSinkType struct {
	value *SinkType
	isSet bool
}

func (v NullableSinkType) Get() *SinkType {
	return v.value
}

func (v *NullableSinkType) Set(val *SinkType) {
	v.value = val
	v.isSet = true
}

func (v NullableSinkType) IsSet() bool {
	return v.isSet
}

func (v *NullableSinkType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSinkType(val *SinkType) *NullableSinkType {
	return &NullableSinkType{value: val, isSet: true}
}

func (v NullableSinkType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSinkType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
