/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the KeysRotateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeysRotateRequest{}

// KeysRotateRequest Body for POST /v1/keys/rotate. Carries the single artifact a rotating plexd Node submits to complete a mesh-key rotation: the freshly-generated Curve25519 public key.
type KeysRotateRequest struct {
	// The Node's freshly-generated Curve25519 (WireGuard) public key, 32 bytes, base64-encoded with standard padding. RFC 7748 §5 fixes the curve to a 32-byte little-endian point encoding, so any other decoded length is rejected with 422 `keys_rotate_public_key_invalid`; the all-zero degenerate value (a known small-order point) is rejected with the same code. A key byte-identical to the Node's current public key is rejected with 422 `keys_rotate_public_key_unchanged`.
	NewPublicKey         string `json:"new_public_key"`
	AdditionalProperties map[string]interface{}
}

type _KeysRotateRequest KeysRotateRequest

// NewKeysRotateRequest instantiates a new KeysRotateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeysRotateRequest(newPublicKey string) *KeysRotateRequest {
	this := KeysRotateRequest{}
	this.NewPublicKey = newPublicKey
	return &this
}

// NewKeysRotateRequestWithDefaults instantiates a new KeysRotateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeysRotateRequestWithDefaults() *KeysRotateRequest {
	this := KeysRotateRequest{}
	return &this
}

// GetNewPublicKey returns the NewPublicKey field value
func (o *KeysRotateRequest) GetNewPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewPublicKey
}

// GetNewPublicKeyOk returns a tuple with the NewPublicKey field value
// and a boolean to check if the value has been set.
func (o *KeysRotateRequest) GetNewPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewPublicKey, true
}

// SetNewPublicKey sets field value
func (o *KeysRotateRequest) SetNewPublicKey(v string) {
	o.NewPublicKey = v
}

func (o KeysRotateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeysRotateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["new_public_key"] = o.NewPublicKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *KeysRotateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"new_public_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeysRotateRequest := _KeysRotateRequest{}

	err = json.Unmarshal(data, &varKeysRotateRequest)

	if err != nil {
		return err
	}

	*o = KeysRotateRequest(varKeysRotateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "new_public_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKeysRotateRequest struct {
	value *KeysRotateRequest
	isSet bool
}

func (v NullableKeysRotateRequest) Get() *KeysRotateRequest {
	return v.value
}

func (v *NullableKeysRotateRequest) Set(val *KeysRotateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKeysRotateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKeysRotateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeysRotateRequest(val *KeysRotateRequest) *NullableKeysRotateRequest {
	return &NullableKeysRotateRequest{value: val, isSet: true}
}

func (v NullableKeysRotateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeysRotateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
