/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the ProviderBundleList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBundleList{}

// ProviderBundleList Page of provider bundles returned by `GET /v1/provider-bundles`. The window is computed by the persistence layer in slug order; per-row visibility is layered on top so the `items` array is the subset the caller is authorised to see.
type ProviderBundleList struct {
	// Provider bundles in the current page.
	Items []ProviderBundleResponse `json:"items"`
	// Continuation token for the next page. Absent when the iteration has reached end-of-stream. The encoding is HMAC-signed by the server so a tampered cursor surfaces as `400` on the next call.
	NextCursor           *string `json:"next_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProviderBundleList ProviderBundleList

// NewProviderBundleList instantiates a new ProviderBundleList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBundleList(items []ProviderBundleResponse) *ProviderBundleList {
	this := ProviderBundleList{}
	this.Items = items
	return &this
}

// NewProviderBundleListWithDefaults instantiates a new ProviderBundleList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBundleListWithDefaults() *ProviderBundleList {
	this := ProviderBundleList{}
	return &this
}

// GetItems returns the Items field value
func (o *ProviderBundleList) GetItems() []ProviderBundleResponse {
	if o == nil {
		var ret []ProviderBundleResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleList) GetItemsOk() ([]ProviderBundleResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ProviderBundleList) SetItems(v []ProviderBundleResponse) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *ProviderBundleList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderBundleList) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *ProviderBundleList) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *ProviderBundleList) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o ProviderBundleList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBundleList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProviderBundleList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderBundleList := _ProviderBundleList{}

	err = json.Unmarshal(data, &varProviderBundleList)

	if err != nil {
		return err
	}

	*o = ProviderBundleList(varProviderBundleList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "next_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProviderBundleList struct {
	value *ProviderBundleList
	isSet bool
}

func (v NullableProviderBundleList) Get() *ProviderBundleList {
	return v.value
}

func (v *NullableProviderBundleList) Set(val *ProviderBundleList) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBundleList) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBundleList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBundleList(val *ProviderBundleList) *NullableProviderBundleList {
	return &NullableProviderBundleList{value: val, isSet: true}
}

func (v NullableProviderBundleList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBundleList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
