/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BlueprintResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintResponse{}

// BlueprintResponse Hydrated projection of a Blueprint Catalog entry. The shape is shared by `ListBlueprints` and `GetBlueprint` — `ListBlueprints` returns it with an empty `versions` array, `GetBlueprint` returns it with the Blueprint's ordered versions.
type BlueprintResponse struct {
	// Blueprint identifier (UUIDv7).
	Id string `json:"id"`
	// Kebab-case URL handle, unique across the catalogue.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// Owning Domain when the Blueprint is scoped to a single Domain. `null` when the entry is catalogue-wide.
	DomainId *string `json:"domain_id,omitempty"`
	// Human-readable Blueprint name.
	DisplayName string `json:"display_name"`
	// Optional free-form Blueprint description. Empty when the catalogue entry declares none.
	Description *string                 `json:"description,omitempty"`
	Status      BlueprintResponseStatus `json:"status"`
	// Blueprint creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-modified timestamp (UTC).
	UpdatedAt time.Time `json:"updated_at"`
	// Ordered Blueprint versions. Empty on the `ListBlueprints` projection; populated on `GetBlueprint`.
	Versions             []BlueprintVersionResponse `json:"versions"`
	AdditionalProperties map[string]interface{}
}

type _BlueprintResponse BlueprintResponse

// NewBlueprintResponse instantiates a new BlueprintResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintResponse(id string, slug string, displayName string, status BlueprintResponseStatus, createdAt time.Time, updatedAt time.Time, versions []BlueprintVersionResponse) *BlueprintResponse {
	this := BlueprintResponse{}
	this.Id = id
	this.Slug = slug
	this.DisplayName = displayName
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Versions = versions
	return &this
}

// NewBlueprintResponseWithDefaults instantiates a new BlueprintResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintResponseWithDefaults() *BlueprintResponse {
	this := BlueprintResponse{}
	return &this
}

// GetId returns the Id field value
func (o *BlueprintResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BlueprintResponse) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *BlueprintResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *BlueprintResponse) SetSlug(v string) {
	o.Slug = v
}

// GetDomainId returns the DomainId field value if set, zero value otherwise.
func (o *BlueprintResponse) GetDomainId() string {
	if o == nil || IsNil(o.DomainId) {
		var ret string
		return ret
	}
	return *o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.DomainId) {
		return nil, false
	}
	return o.DomainId, true
}

// HasDomainId returns a boolean if a field has been set.
func (o *BlueprintResponse) HasDomainId() bool {
	if o != nil && !IsNil(o.DomainId) {
		return true
	}

	return false
}

// SetDomainId gets a reference to the given string and assigns it to the DomainId field.
func (o *BlueprintResponse) SetDomainId(v string) {
	o.DomainId = &v
}

// GetDisplayName returns the DisplayName field value
func (o *BlueprintResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *BlueprintResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BlueprintResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BlueprintResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BlueprintResponse) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value
func (o *BlueprintResponse) GetStatus() BlueprintResponseStatus {
	if o == nil {
		var ret BlueprintResponseStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetStatusOk() (*BlueprintResponseStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BlueprintResponse) SetStatus(v BlueprintResponseStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BlueprintResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BlueprintResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BlueprintResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BlueprintResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetVersions returns the Versions field value
func (o *BlueprintResponse) GetVersions() []BlueprintVersionResponse {
	if o == nil {
		var ret []BlueprintVersionResponse
		return ret
	}

	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value
// and a boolean to check if the value has been set.
func (o *BlueprintResponse) GetVersionsOk() ([]BlueprintVersionResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Versions, true
}

// SetVersions sets field value
func (o *BlueprintResponse) SetVersions(v []BlueprintVersionResponse) {
	o.Versions = v
}

func (o BlueprintResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	if !IsNil(o.DomainId) {
		toSerialize["domain_id"] = o.DomainId
	}
	toSerialize["display_name"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["versions"] = o.Versions

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BlueprintResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"display_name",
		"status",
		"created_at",
		"updated_at",
		"versions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprintResponse := _BlueprintResponse{}

	err = json.Unmarshal(data, &varBlueprintResponse)

	if err != nil {
		return err
	}

	*o = BlueprintResponse(varBlueprintResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "domain_id")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "versions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBlueprintResponse struct {
	value *BlueprintResponse
	isSet bool
}

func (v NullableBlueprintResponse) Get() *BlueprintResponse {
	return v.value
}

func (v *NullableBlueprintResponse) Set(val *BlueprintResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintResponse(val *BlueprintResponse) *NullableBlueprintResponse {
	return &NullableBlueprintResponse{value: val, isSet: true}
}

func (v NullableBlueprintResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
