/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// PolicyAction Verdict pronounced on a matching packet. Closed set — values outside this enum reject at the aggregate boundary with `422 unknown_action`.
type PolicyAction string

// List of PolicyAction
const (
	POLICYACTION_ALLOW                    PolicyAction = "allow"
	POLICYACTION_DENY                     PolicyAction = "deny"
	POLICYACTION_LOG                      PolicyAction = "log"
	POLICYACTION_UNKNOWN_DEFAULT_OPEN_API PolicyAction = "unknown_default_open_api"
)

// All allowed values of PolicyAction enum
var AllowedPolicyActionEnumValues = []PolicyAction{
	"allow",
	"deny",
	"log",
	"unknown_default_open_api",
}

func (v *PolicyAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PolicyAction(value)
	for _, existing := range AllowedPolicyActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = POLICYACTION_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewPolicyActionFromValue returns a pointer to a valid PolicyAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPolicyActionFromValue(v string) (*PolicyAction, error) {
	ev := PolicyAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PolicyAction: valid values are %v", v, AllowedPolicyActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PolicyAction) IsValid() bool {
	for _, existing := range AllowedPolicyActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PolicyAction value
func (v PolicyAction) Ptr() *PolicyAction {
	return &v
}

type NullablePolicyAction struct {
	value *PolicyAction
	isSet bool
}

func (v NullablePolicyAction) Get() *PolicyAction {
	return v.value
}

func (v *NullablePolicyAction) Set(val *PolicyAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyAction(val *PolicyAction) *NullablePolicyAction {
	return &NullablePolicyAction{value: val, isSet: true}
}

func (v NullablePolicyAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
