/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SinkCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SinkCredential{}

// SinkCredential Where a tenant sink's connection material lives. The projection carries the KV coordinates only — never the material itself, which stays in the secret store and is read at delivery time.
type SinkCredential struct {
	// KV mount the material lives under.
	KvMount string `json:"kv_mount"`
	// Path the material lives at under the mount. It is derived server-side from the owning Domain and the sink id, so a reference can never address another tenant's material.
	KvPath string `json:"kv_path"`
	// KV version to read. Absent or `0` reads the latest one.
	KvVersion *int64 `json:"kv_version,omitempty"`
}

type _SinkCredential SinkCredential

// NewSinkCredential instantiates a new SinkCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSinkCredential(kvMount string, kvPath string) *SinkCredential {
	this := SinkCredential{}
	this.KvMount = kvMount
	this.KvPath = kvPath
	return &this
}

// NewSinkCredentialWithDefaults instantiates a new SinkCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSinkCredentialWithDefaults() *SinkCredential {
	this := SinkCredential{}
	return &this
}

// GetKvMount returns the KvMount field value
func (o *SinkCredential) GetKvMount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KvMount
}

// GetKvMountOk returns a tuple with the KvMount field value
// and a boolean to check if the value has been set.
func (o *SinkCredential) GetKvMountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KvMount, true
}

// SetKvMount sets field value
func (o *SinkCredential) SetKvMount(v string) {
	o.KvMount = v
}

// GetKvPath returns the KvPath field value
func (o *SinkCredential) GetKvPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KvPath
}

// GetKvPathOk returns a tuple with the KvPath field value
// and a boolean to check if the value has been set.
func (o *SinkCredential) GetKvPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KvPath, true
}

// SetKvPath sets field value
func (o *SinkCredential) SetKvPath(v string) {
	o.KvPath = v
}

// GetKvVersion returns the KvVersion field value if set, zero value otherwise.
func (o *SinkCredential) GetKvVersion() int64 {
	if o == nil || IsNil(o.KvVersion) {
		var ret int64
		return ret
	}
	return *o.KvVersion
}

// GetKvVersionOk returns a tuple with the KvVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinkCredential) GetKvVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.KvVersion) {
		return nil, false
	}
	return o.KvVersion, true
}

// HasKvVersion returns a boolean if a field has been set.
func (o *SinkCredential) HasKvVersion() bool {
	if o != nil && !IsNil(o.KvVersion) {
		return true
	}

	return false
}

// SetKvVersion gets a reference to the given int64 and assigns it to the KvVersion field.
func (o *SinkCredential) SetKvVersion(v int64) {
	o.KvVersion = &v
}

func (o SinkCredential) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SinkCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kv_mount"] = o.KvMount
	toSerialize["kv_path"] = o.KvPath
	if !IsNil(o.KvVersion) {
		toSerialize["kv_version"] = o.KvVersion
	}
	return toSerialize, nil
}

func (o *SinkCredential) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kv_mount",
		"kv_path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSinkCredential := _SinkCredential{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSinkCredential)

	if err != nil {
		return err
	}

	*o = SinkCredential(varSinkCredential)

	return err
}

type NullableSinkCredential struct {
	value *SinkCredential
	isSet bool
}

func (v NullableSinkCredential) Get() *SinkCredential {
	return v.value
}

func (v *NullableSinkCredential) Set(val *SinkCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableSinkCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableSinkCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSinkCredential(val *SinkCredential) *NullableSinkCredential {
	return &NullableSinkCredential{value: val, isSet: true}
}

func (v NullableSinkCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSinkCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
