/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the BridgeIngressRuleList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BridgeIngressRuleList{}

// BridgeIngressRuleList Public-ingress rules on a bridge Resource, returned by `ListBridgeIngressRules`. Ordered by slug ascending.
type BridgeIngressRuleList struct {
	// Rules ordered by slug ascending.
	Rules                []BridgeIngressRuleResponse `json:"rules"`
	AdditionalProperties map[string]interface{}
}

type _BridgeIngressRuleList BridgeIngressRuleList

// NewBridgeIngressRuleList instantiates a new BridgeIngressRuleList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBridgeIngressRuleList(rules []BridgeIngressRuleResponse) *BridgeIngressRuleList {
	this := BridgeIngressRuleList{}
	this.Rules = rules
	return &this
}

// NewBridgeIngressRuleListWithDefaults instantiates a new BridgeIngressRuleList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBridgeIngressRuleListWithDefaults() *BridgeIngressRuleList {
	this := BridgeIngressRuleList{}
	return &this
}

// GetRules returns the Rules field value
func (o *BridgeIngressRuleList) GetRules() []BridgeIngressRuleResponse {
	if o == nil {
		var ret []BridgeIngressRuleResponse
		return ret
	}

	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleList) GetRulesOk() ([]BridgeIngressRuleResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules, true
}

// SetRules sets field value
func (o *BridgeIngressRuleList) SetRules(v []BridgeIngressRuleResponse) {
	o.Rules = v
}

func (o BridgeIngressRuleList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BridgeIngressRuleList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rules"] = o.Rules

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BridgeIngressRuleList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBridgeIngressRuleList := _BridgeIngressRuleList{}

	err = json.Unmarshal(data, &varBridgeIngressRuleList)

	if err != nil {
		return err
	}

	*o = BridgeIngressRuleList(varBridgeIngressRuleList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rules")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBridgeIngressRuleList struct {
	value *BridgeIngressRuleList
	isSet bool
}

func (v NullableBridgeIngressRuleList) Get() *BridgeIngressRuleList {
	return v.value
}

func (v *NullableBridgeIngressRuleList) Set(val *BridgeIngressRuleList) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgeIngressRuleList) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgeIngressRuleList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgeIngressRuleList(val *BridgeIngressRuleList) *NullableBridgeIngressRuleList {
	return &NullableBridgeIngressRuleList{value: val, isSet: true}
}

func (v NullableBridgeIngressRuleList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgeIngressRuleList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
