/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the RelationTupleCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RelationTupleCreateRequest{}

// RelationTupleCreateRequest Body for `POST /v1/authz/relation-tuples`. Field set mirrors the relation-tuple aggregate's `NewRelationTuple` invariants.
type RelationTupleCreateRequest struct {
	// Object reference of the subject side.
	Subject string `json:"subject"`
	// Relation name.
	Relation string `json:"relation"`
	// Object reference of the resource side.
	Resource string `json:"resource"`
	// Optional caveat program name to attach to the tuple. When set, SpiceDB evaluates the caveat against the supplied `caveat_context` at every Check.
	CaveatName *string `json:"caveat_name,omitempty"`
	// Optional set of caveat field NAMES the tuple binds. NAMES only — values never cross the contract boundary.
	CaveatContext        map[string]interface{} `json:"caveat_context,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RelationTupleCreateRequest RelationTupleCreateRequest

// NewRelationTupleCreateRequest instantiates a new RelationTupleCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRelationTupleCreateRequest(subject string, relation string, resource string) *RelationTupleCreateRequest {
	this := RelationTupleCreateRequest{}
	this.Subject = subject
	this.Relation = relation
	this.Resource = resource
	return &this
}

// NewRelationTupleCreateRequestWithDefaults instantiates a new RelationTupleCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRelationTupleCreateRequestWithDefaults() *RelationTupleCreateRequest {
	this := RelationTupleCreateRequest{}
	return &this
}

// GetSubject returns the Subject field value
func (o *RelationTupleCreateRequest) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *RelationTupleCreateRequest) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *RelationTupleCreateRequest) SetSubject(v string) {
	o.Subject = v
}

// GetRelation returns the Relation field value
func (o *RelationTupleCreateRequest) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *RelationTupleCreateRequest) GetRelationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *RelationTupleCreateRequest) SetRelation(v string) {
	o.Relation = v
}

// GetResource returns the Resource field value
func (o *RelationTupleCreateRequest) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *RelationTupleCreateRequest) GetResourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *RelationTupleCreateRequest) SetResource(v string) {
	o.Resource = v
}

// GetCaveatName returns the CaveatName field value if set, zero value otherwise.
func (o *RelationTupleCreateRequest) GetCaveatName() string {
	if o == nil || IsNil(o.CaveatName) {
		var ret string
		return ret
	}
	return *o.CaveatName
}

// GetCaveatNameOk returns a tuple with the CaveatName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationTupleCreateRequest) GetCaveatNameOk() (*string, bool) {
	if o == nil || IsNil(o.CaveatName) {
		return nil, false
	}
	return o.CaveatName, true
}

// HasCaveatName returns a boolean if a field has been set.
func (o *RelationTupleCreateRequest) HasCaveatName() bool {
	if o != nil && !IsNil(o.CaveatName) {
		return true
	}

	return false
}

// SetCaveatName gets a reference to the given string and assigns it to the CaveatName field.
func (o *RelationTupleCreateRequest) SetCaveatName(v string) {
	o.CaveatName = &v
}

// GetCaveatContext returns the CaveatContext field value if set, zero value otherwise.
func (o *RelationTupleCreateRequest) GetCaveatContext() map[string]interface{} {
	if o == nil || IsNil(o.CaveatContext) {
		var ret map[string]interface{}
		return ret
	}
	return o.CaveatContext
}

// GetCaveatContextOk returns a tuple with the CaveatContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RelationTupleCreateRequest) GetCaveatContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CaveatContext) {
		return map[string]interface{}{}, false
	}
	return o.CaveatContext, true
}

// HasCaveatContext returns a boolean if a field has been set.
func (o *RelationTupleCreateRequest) HasCaveatContext() bool {
	if o != nil && !IsNil(o.CaveatContext) {
		return true
	}

	return false
}

// SetCaveatContext gets a reference to the given map[string]interface{} and assigns it to the CaveatContext field.
func (o *RelationTupleCreateRequest) SetCaveatContext(v map[string]interface{}) {
	o.CaveatContext = v
}

func (o RelationTupleCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RelationTupleCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subject"] = o.Subject
	toSerialize["relation"] = o.Relation
	toSerialize["resource"] = o.Resource
	if !IsNil(o.CaveatName) {
		toSerialize["caveat_name"] = o.CaveatName
	}
	if !IsNil(o.CaveatContext) {
		toSerialize["caveat_context"] = o.CaveatContext
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RelationTupleCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subject",
		"relation",
		"resource",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRelationTupleCreateRequest := _RelationTupleCreateRequest{}

	err = json.Unmarshal(data, &varRelationTupleCreateRequest)

	if err != nil {
		return err
	}

	*o = RelationTupleCreateRequest(varRelationTupleCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subject")
		delete(additionalProperties, "relation")
		delete(additionalProperties, "resource")
		delete(additionalProperties, "caveat_name")
		delete(additionalProperties, "caveat_context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRelationTupleCreateRequest struct {
	value *RelationTupleCreateRequest
	isSet bool
}

func (v NullableRelationTupleCreateRequest) Get() *RelationTupleCreateRequest {
	return v.value
}

func (v *NullableRelationTupleCreateRequest) Set(val *RelationTupleCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRelationTupleCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRelationTupleCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelationTupleCreateRequest(val *RelationTupleCreateRequest) *NullableRelationTupleCreateRequest {
	return &NullableRelationTupleCreateRequest{value: val, isSet: true}
}

func (v NullableRelationTupleCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelationTupleCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
