/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the APITokenRotateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APITokenRotateResponse{}

// APITokenRotateResponse Response for POST /v1/auth/tokens/{id}/rotate. The `Sunset` header names the retirement deadline of the rotated-from plaintext.
type APITokenRotateResponse struct {
	// Token identifier (UUIDv7).
	Id string `json:"id"`
	// New psk-shaped plaintext; returned exactly once.
	Plaintext string `json:"plaintext"`
	// Environment segment embedded in the plaintext.
	EnvPrefix string `json:"env_prefix"`
	// Expiry timestamp of the new plaintext.
	ExpiresAt time.Time `json:"expires_at"`
	// Retirement deadline of the rotated-from plaintext. Matches the value advertised in the `Sunset` response header.
	RotationDeadline     time.Time `json:"rotation_deadline"`
	AdditionalProperties map[string]interface{}
}

type _APITokenRotateResponse APITokenRotateResponse

// NewAPITokenRotateResponse instantiates a new APITokenRotateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPITokenRotateResponse(id string, plaintext string, envPrefix string, expiresAt time.Time, rotationDeadline time.Time) *APITokenRotateResponse {
	this := APITokenRotateResponse{}
	this.Id = id
	this.Plaintext = plaintext
	this.EnvPrefix = envPrefix
	this.ExpiresAt = expiresAt
	this.RotationDeadline = rotationDeadline
	return &this
}

// NewAPITokenRotateResponseWithDefaults instantiates a new APITokenRotateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPITokenRotateResponseWithDefaults() *APITokenRotateResponse {
	this := APITokenRotateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *APITokenRotateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *APITokenRotateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *APITokenRotateResponse) SetId(v string) {
	o.Id = v
}

// GetPlaintext returns the Plaintext field value
func (o *APITokenRotateResponse) GetPlaintext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plaintext
}

// GetPlaintextOk returns a tuple with the Plaintext field value
// and a boolean to check if the value has been set.
func (o *APITokenRotateResponse) GetPlaintextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plaintext, true
}

// SetPlaintext sets field value
func (o *APITokenRotateResponse) SetPlaintext(v string) {
	o.Plaintext = v
}

// GetEnvPrefix returns the EnvPrefix field value
func (o *APITokenRotateResponse) GetEnvPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnvPrefix
}

// GetEnvPrefixOk returns a tuple with the EnvPrefix field value
// and a boolean to check if the value has been set.
func (o *APITokenRotateResponse) GetEnvPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnvPrefix, true
}

// SetEnvPrefix sets field value
func (o *APITokenRotateResponse) SetEnvPrefix(v string) {
	o.EnvPrefix = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *APITokenRotateResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *APITokenRotateResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *APITokenRotateResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetRotationDeadline returns the RotationDeadline field value
func (o *APITokenRotateResponse) GetRotationDeadline() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.RotationDeadline
}

// GetRotationDeadlineOk returns a tuple with the RotationDeadline field value
// and a boolean to check if the value has been set.
func (o *APITokenRotateResponse) GetRotationDeadlineOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotationDeadline, true
}

// SetRotationDeadline sets field value
func (o *APITokenRotateResponse) SetRotationDeadline(v time.Time) {
	o.RotationDeadline = v
}

func (o APITokenRotateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APITokenRotateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["plaintext"] = o.Plaintext
	toSerialize["env_prefix"] = o.EnvPrefix
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["rotation_deadline"] = o.RotationDeadline

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *APITokenRotateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"plaintext",
		"env_prefix",
		"expires_at",
		"rotation_deadline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPITokenRotateResponse := _APITokenRotateResponse{}

	err = json.Unmarshal(data, &varAPITokenRotateResponse)

	if err != nil {
		return err
	}

	*o = APITokenRotateResponse(varAPITokenRotateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "plaintext")
		delete(additionalProperties, "env_prefix")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "rotation_deadline")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAPITokenRotateResponse struct {
	value *APITokenRotateResponse
	isSet bool
}

func (v NullableAPITokenRotateResponse) Get() *APITokenRotateResponse {
	return v.value
}

func (v *NullableAPITokenRotateResponse) Set(val *APITokenRotateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAPITokenRotateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAPITokenRotateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPITokenRotateResponse(val *APITokenRotateResponse) *NullableAPITokenRotateResponse {
	return &NullableAPITokenRotateResponse{value: val, isSet: true}
}

func (v NullableAPITokenRotateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPITokenRotateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
