/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// CatalogSourceResponseStatus Lifecycle status.
type CatalogSourceResponseStatus string

// List of CatalogSourceResponse_status
const (
	CATALOGSOURCERESPONSESTATUS_ACTIVE                   CatalogSourceResponseStatus = "active"
	CATALOGSOURCERESPONSESTATUS_DISABLED                 CatalogSourceResponseStatus = "disabled"
	CATALOGSOURCERESPONSESTATUS_UNKNOWN_DEFAULT_OPEN_API CatalogSourceResponseStatus = "unknown_default_open_api"
)

// All allowed values of CatalogSourceResponseStatus enum
var AllowedCatalogSourceResponseStatusEnumValues = []CatalogSourceResponseStatus{
	"active",
	"disabled",
	"unknown_default_open_api",
}

func (v *CatalogSourceResponseStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CatalogSourceResponseStatus(value)
	for _, existing := range AllowedCatalogSourceResponseStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = CATALOGSOURCERESPONSESTATUS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewCatalogSourceResponseStatusFromValue returns a pointer to a valid CatalogSourceResponseStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCatalogSourceResponseStatusFromValue(v string) (*CatalogSourceResponseStatus, error) {
	ev := CatalogSourceResponseStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CatalogSourceResponseStatus: valid values are %v", v, AllowedCatalogSourceResponseStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CatalogSourceResponseStatus) IsValid() bool {
	for _, existing := range AllowedCatalogSourceResponseStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CatalogSourceResponse_status value
func (v CatalogSourceResponseStatus) Ptr() *CatalogSourceResponseStatus {
	return &v
}

type NullableCatalogSourceResponseStatus struct {
	value *CatalogSourceResponseStatus
	isSet bool
}

func (v NullableCatalogSourceResponseStatus) Get() *CatalogSourceResponseStatus {
	return v.value
}

func (v *NullableCatalogSourceResponseStatus) Set(val *CatalogSourceResponseStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogSourceResponseStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogSourceResponseStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogSourceResponseStatus(val *CatalogSourceResponseStatus) *NullableCatalogSourceResponseStatus {
	return &NullableCatalogSourceResponseStatus{value: val, isSet: true}
}

func (v NullableCatalogSourceResponseStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogSourceResponseStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
