/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Policy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Policy{}

// Policy Network Policy aggregate. Each Policy belongs to exactly one Project (the ReBAC parent), carries an append-only revision history, and has at any moment exactly one live head revision. The head pointer advances atomically inside the same transaction that lands a new revision; a concurrent PATCH that loses the partial-unique-head race surfaces as `409 revision_conflict`.
type Policy struct {
	// Policy identifier (UUIDv7).
	Id string `json:"id"`
	// Owning Project (UUIDv7).
	ProjectId string `json:"project_id"`
	// Stable kebab-case handle for the Policy. Unique within the owning Project — a duplicate `(project_id, slug)` rejects with `409 policy_slug_taken`.
	Slug string `json:"slug" validate:"regexp=^[a-z][a-z0-9-]*$"`
	// Human-readable label. Optional — falls back to `slug` in renderings when empty.
	DisplayName *string `json:"display_name,omitempty"`
	// Identifier of the current head revision. Advances every PATCH inside the same transaction that inserts the new revision row.
	HeadRevisionId string    `json:"head_revision_id"`
	CreatedAt      time.Time `json:"created_at"`
	// Timestamp of the last head-revision advance. Equal to `created_at` on a freshly-created Policy.
	UpdatedAt time.Time `json:"updated_at"`
	// Fully-hydrated head revision. Returned on `GET` of a single Policy; intentionally omitted from list entries to keep the page payload bounded — callers that need rule lists per row iterate the list and then `GET` each Policy.
	Head                 *PolicyRevision `json:"head,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Policy Policy

// NewPolicy instantiates a new Policy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicy(id string, projectId string, slug string, headRevisionId string, createdAt time.Time, updatedAt time.Time) *Policy {
	this := Policy{}
	this.Id = id
	this.ProjectId = projectId
	this.Slug = slug
	this.HeadRevisionId = headRevisionId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPolicyWithDefaults instantiates a new Policy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyWithDefaults() *Policy {
	this := Policy{}
	return &this
}

// GetId returns the Id field value
func (o *Policy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Policy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Policy) SetId(v string) {
	o.Id = v
}

// GetProjectId returns the ProjectId field value
func (o *Policy) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *Policy) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *Policy) SetProjectId(v string) {
	o.ProjectId = v
}

// GetSlug returns the Slug field value
func (o *Policy) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *Policy) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *Policy) SetSlug(v string) {
	o.Slug = v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Policy) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Policy) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Policy) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetHeadRevisionId returns the HeadRevisionId field value
func (o *Policy) GetHeadRevisionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HeadRevisionId
}

// GetHeadRevisionIdOk returns a tuple with the HeadRevisionId field value
// and a boolean to check if the value has been set.
func (o *Policy) GetHeadRevisionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeadRevisionId, true
}

// SetHeadRevisionId sets field value
func (o *Policy) SetHeadRevisionId(v string) {
	o.HeadRevisionId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Policy) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Policy) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Policy) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Policy) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Policy) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Policy) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetHead returns the Head field value if set, zero value otherwise.
func (o *Policy) GetHead() PolicyRevision {
	if o == nil || IsNil(o.Head) {
		var ret PolicyRevision
		return ret
	}
	return *o.Head
}

// GetHeadOk returns a tuple with the Head field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetHeadOk() (*PolicyRevision, bool) {
	if o == nil || IsNil(o.Head) {
		return nil, false
	}
	return o.Head, true
}

// HasHead returns a boolean if a field has been set.
func (o *Policy) HasHead() bool {
	if o != nil && !IsNil(o.Head) {
		return true
	}

	return false
}

// SetHead gets a reference to the given PolicyRevision and assigns it to the Head field.
func (o *Policy) SetHead(v PolicyRevision) {
	o.Head = &v
}

func (o Policy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Policy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["project_id"] = o.ProjectId
	toSerialize["slug"] = o.Slug
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	toSerialize["head_revision_id"] = o.HeadRevisionId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Head) {
		toSerialize["head"] = o.Head
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Policy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"project_id",
		"slug",
		"head_revision_id",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicy := _Policy{}

	err = json.Unmarshal(data, &varPolicy)

	if err != nil {
		return err
	}

	*o = Policy(varPolicy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "project_id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "head_revision_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "head")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicy struct {
	value *Policy
	isSet bool
}

func (v NullablePolicy) Get() *Policy {
	return v.value
}

func (v *NullablePolicy) Set(val *Policy) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicy(val *Policy) *NullablePolicy {
	return &NullablePolicy{value: val, isSet: true}
}

func (v NullablePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
