/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// BackupPriority Disaster-recovery restore priority of a backed-up store: `P0` is the most critical (restore first), `P3` the least critical (gaps self-heal after restore).
type BackupPriority string

// List of BackupPriority
const (
	BACKUPPRIORITY_BackupPriorityP0         BackupPriority = "P0"
	BACKUPPRIORITY_BackupPriorityP1         BackupPriority = "P1"
	BACKUPPRIORITY_BackupPriorityP2         BackupPriority = "P2"
	BACKUPPRIORITY_BackupPriorityP3         BackupPriority = "P3"
	BACKUPPRIORITY_UNKNOWN_DEFAULT_OPEN_API BackupPriority = "unknown_default_open_api"
)

// All allowed values of BackupPriority enum
var AllowedBackupPriorityEnumValues = []BackupPriority{
	"P0",
	"P1",
	"P2",
	"P3",
	"unknown_default_open_api",
}

func (v *BackupPriority) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BackupPriority(value)
	for _, existing := range AllowedBackupPriorityEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = BACKUPPRIORITY_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewBackupPriorityFromValue returns a pointer to a valid BackupPriority
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBackupPriorityFromValue(v string) (*BackupPriority, error) {
	ev := BackupPriority(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BackupPriority: valid values are %v", v, AllowedBackupPriorityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BackupPriority) IsValid() bool {
	for _, existing := range AllowedBackupPriorityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BackupPriority value
func (v BackupPriority) Ptr() *BackupPriority {
	return &v
}

type NullableBackupPriority struct {
	value *BackupPriority
	isSet bool
}

func (v NullableBackupPriority) Get() *BackupPriority {
	return v.value
}

func (v *NullableBackupPriority) Set(val *BackupPriority) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupPriority) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupPriority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupPriority(val *BackupPriority) *NullableBackupPriority {
	return &NullableBackupPriority{value: val, isSet: true}
}

func (v NullableBackupPriority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupPriority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
