/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the BridgeIngressRuleCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BridgeIngressRuleCreateRequest{}

// BridgeIngressRuleCreateRequest Body for `CreateBridgeIngressRule`. Creates one public-ingress rule keyed by `(resource_id, slug)`, with an additional `(resource_id, sni_host)` uniqueness constraint.
type BridgeIngressRuleCreateRequest struct {
	// Stable identity of the rule within its Resource. Unique per `(resource_id, slug)`; a collision surfaces as `409 slug_conflict`.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// TLS SNI host the rule terminates. Unique per `(resource_id, sni_host)`; a collision surfaces as `409 slug_conflict`.
	SniHost string `json:"sni_host"`
	// Node the rule forwards to. A Node outside the bridge Resource's owning Domain surfaces as `400 target_node_not_in_domain`.
	TargetNodeId string `json:"target_node_id"`
	// TCP port on the target Node. Outside `1..65535` the write is rejected with `400 relay_port_out_of_range`.
	TargetPort int32 `json:"target_port"`
	// Optional opaque reference to the ACME account used to issue the rule's certificate. `null` or absent means the operator supplies certificates out of band rather than via ACME issuance.
	AcmeAccountRef       *string `json:"acme_account_ref,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BridgeIngressRuleCreateRequest BridgeIngressRuleCreateRequest

// NewBridgeIngressRuleCreateRequest instantiates a new BridgeIngressRuleCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBridgeIngressRuleCreateRequest(slug string, sniHost string, targetNodeId string, targetPort int32) *BridgeIngressRuleCreateRequest {
	this := BridgeIngressRuleCreateRequest{}
	this.Slug = slug
	this.SniHost = sniHost
	this.TargetNodeId = targetNodeId
	this.TargetPort = targetPort
	return &this
}

// NewBridgeIngressRuleCreateRequestWithDefaults instantiates a new BridgeIngressRuleCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBridgeIngressRuleCreateRequestWithDefaults() *BridgeIngressRuleCreateRequest {
	this := BridgeIngressRuleCreateRequest{}
	return &this
}

// GetSlug returns the Slug field value
func (o *BridgeIngressRuleCreateRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleCreateRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *BridgeIngressRuleCreateRequest) SetSlug(v string) {
	o.Slug = v
}

// GetSniHost returns the SniHost field value
func (o *BridgeIngressRuleCreateRequest) GetSniHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SniHost
}

// GetSniHostOk returns a tuple with the SniHost field value
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleCreateRequest) GetSniHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SniHost, true
}

// SetSniHost sets field value
func (o *BridgeIngressRuleCreateRequest) SetSniHost(v string) {
	o.SniHost = v
}

// GetTargetNodeId returns the TargetNodeId field value
func (o *BridgeIngressRuleCreateRequest) GetTargetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetNodeId
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleCreateRequest) GetTargetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNodeId, true
}

// SetTargetNodeId sets field value
func (o *BridgeIngressRuleCreateRequest) SetTargetNodeId(v string) {
	o.TargetNodeId = v
}

// GetTargetPort returns the TargetPort field value
func (o *BridgeIngressRuleCreateRequest) GetTargetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetPort
}

// GetTargetPortOk returns a tuple with the TargetPort field value
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleCreateRequest) GetTargetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetPort, true
}

// SetTargetPort sets field value
func (o *BridgeIngressRuleCreateRequest) SetTargetPort(v int32) {
	o.TargetPort = v
}

// GetAcmeAccountRef returns the AcmeAccountRef field value if set, zero value otherwise.
func (o *BridgeIngressRuleCreateRequest) GetAcmeAccountRef() string {
	if o == nil || IsNil(o.AcmeAccountRef) {
		var ret string
		return ret
	}
	return *o.AcmeAccountRef
}

// GetAcmeAccountRefOk returns a tuple with the AcmeAccountRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BridgeIngressRuleCreateRequest) GetAcmeAccountRefOk() (*string, bool) {
	if o == nil || IsNil(o.AcmeAccountRef) {
		return nil, false
	}
	return o.AcmeAccountRef, true
}

// HasAcmeAccountRef returns a boolean if a field has been set.
func (o *BridgeIngressRuleCreateRequest) HasAcmeAccountRef() bool {
	if o != nil && !IsNil(o.AcmeAccountRef) {
		return true
	}

	return false
}

// SetAcmeAccountRef gets a reference to the given string and assigns it to the AcmeAccountRef field.
func (o *BridgeIngressRuleCreateRequest) SetAcmeAccountRef(v string) {
	o.AcmeAccountRef = &v
}

func (o BridgeIngressRuleCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BridgeIngressRuleCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["sni_host"] = o.SniHost
	toSerialize["target_node_id"] = o.TargetNodeId
	toSerialize["target_port"] = o.TargetPort
	if !IsNil(o.AcmeAccountRef) {
		toSerialize["acme_account_ref"] = o.AcmeAccountRef
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BridgeIngressRuleCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"sni_host",
		"target_node_id",
		"target_port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBridgeIngressRuleCreateRequest := _BridgeIngressRuleCreateRequest{}

	err = json.Unmarshal(data, &varBridgeIngressRuleCreateRequest)

	if err != nil {
		return err
	}

	*o = BridgeIngressRuleCreateRequest(varBridgeIngressRuleCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slug")
		delete(additionalProperties, "sni_host")
		delete(additionalProperties, "target_node_id")
		delete(additionalProperties, "target_port")
		delete(additionalProperties, "acme_account_ref")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBridgeIngressRuleCreateRequest struct {
	value *BridgeIngressRuleCreateRequest
	isSet bool
}

func (v NullableBridgeIngressRuleCreateRequest) Get() *BridgeIngressRuleCreateRequest {
	return v.value
}

func (v *NullableBridgeIngressRuleCreateRequest) Set(val *BridgeIngressRuleCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgeIngressRuleCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgeIngressRuleCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgeIngressRuleCreateRequest(val *BridgeIngressRuleCreateRequest) *NullableBridgeIngressRuleCreateRequest {
	return &NullableBridgeIngressRuleCreateRequest{value: val, isSet: true}
}

func (v NullableBridgeIngressRuleCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgeIngressRuleCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
