/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
)

// checks if the SinkSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SinkSettings{}

// SinkSettings Per-type configuration a destination needs beyond its address. Every field is stated on one sink type only; stating one on another type is refused with `422 sink_invalid`.
type SinkSettings struct {
	// Logical stream an `otlp` destination files the delivered telemetry under. Stated on `otlp` sinks only.
	Dataset *string `json:"dataset,omitempty"`
}

// NewSinkSettings instantiates a new SinkSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSinkSettings() *SinkSettings {
	this := SinkSettings{}
	return &this
}

// NewSinkSettingsWithDefaults instantiates a new SinkSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSinkSettingsWithDefaults() *SinkSettings {
	this := SinkSettings{}
	return &this
}

// GetDataset returns the Dataset field value if set, zero value otherwise.
func (o *SinkSettings) GetDataset() string {
	if o == nil || IsNil(o.Dataset) {
		var ret string
		return ret
	}
	return *o.Dataset
}

// GetDatasetOk returns a tuple with the Dataset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SinkSettings) GetDatasetOk() (*string, bool) {
	if o == nil || IsNil(o.Dataset) {
		return nil, false
	}
	return o.Dataset, true
}

// HasDataset returns a boolean if a field has been set.
func (o *SinkSettings) HasDataset() bool {
	if o != nil && !IsNil(o.Dataset) {
		return true
	}

	return false
}

// SetDataset gets a reference to the given string and assigns it to the Dataset field.
func (o *SinkSettings) SetDataset(v string) {
	o.Dataset = &v
}

func (o SinkSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SinkSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dataset) {
		toSerialize["dataset"] = o.Dataset
	}
	return toSerialize, nil
}

type NullableSinkSettings struct {
	value *SinkSettings
	isSet bool
}

func (v NullableSinkSettings) Get() *SinkSettings {
	return v.value
}

func (v *NullableSinkSettings) Set(val *SinkSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableSinkSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSinkSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSinkSettings(val *SinkSettings) *NullableSinkSettings {
	return &NullableSinkSettings{value: val, isSet: true}
}

func (v NullableSinkSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSinkSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
