/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BridgeSiteToSiteTunnelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BridgeSiteToSiteTunnelResponse{}

// BridgeSiteToSiteTunnelResponse Hydrated projection of a bridge site-to-site tunnel. Shared by `CreateBridgeSiteToSiteTunnel`, `GetBridgeSiteToSiteTunnel`, `UpdateBridgeSiteToSiteTunnel`, and the list wrapper.
type BridgeSiteToSiteTunnelResponse struct {
	// Tunnel identifier (UUIDv7).
	Id string `json:"id"`
	// Stable identity of the tunnel within its Resource.
	Slug string                     `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	Kind BridgeSiteToSiteTunnelKind `json:"kind"`
	// Hostname or address of the remote tunnel endpoint.
	RemoteHost string `json:"remote_host"`
	// Port on the remote tunnel endpoint.
	RemotePort int32 `json:"remote_port"`
	// Opaque reference to the tunnel's authentication material in the form `secret:<domain>/<project>/<name>(:<version>)?`.
	AuthSecretRef string `json:"auth_secret_ref"`
	// CIDR prefixes the tunnel routes.
	AllowedSubnets []string                            `json:"allowed_subnets"`
	RoutingPolicy  BridgeSiteToSiteTunnelRoutingPolicy `json:"routing_policy"`
	// Tunnel creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-modified timestamp (UTC).
	UpdatedAt            time.Time `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _BridgeSiteToSiteTunnelResponse BridgeSiteToSiteTunnelResponse

// NewBridgeSiteToSiteTunnelResponse instantiates a new BridgeSiteToSiteTunnelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBridgeSiteToSiteTunnelResponse(id string, slug string, kind BridgeSiteToSiteTunnelKind, remoteHost string, remotePort int32, authSecretRef string, allowedSubnets []string, routingPolicy BridgeSiteToSiteTunnelRoutingPolicy, createdAt time.Time, updatedAt time.Time) *BridgeSiteToSiteTunnelResponse {
	this := BridgeSiteToSiteTunnelResponse{}
	this.Id = id
	this.Slug = slug
	this.Kind = kind
	this.RemoteHost = remoteHost
	this.RemotePort = remotePort
	this.AuthSecretRef = authSecretRef
	this.AllowedSubnets = allowedSubnets
	this.RoutingPolicy = routingPolicy
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBridgeSiteToSiteTunnelResponseWithDefaults instantiates a new BridgeSiteToSiteTunnelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBridgeSiteToSiteTunnelResponseWithDefaults() *BridgeSiteToSiteTunnelResponse {
	this := BridgeSiteToSiteTunnelResponse{}
	return &this
}

// GetId returns the Id field value
func (o *BridgeSiteToSiteTunnelResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetId(v string) {
	o.Id = v
}

// GetSlug returns the Slug field value
func (o *BridgeSiteToSiteTunnelResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetSlug(v string) {
	o.Slug = v
}

// GetKind returns the Kind field value
func (o *BridgeSiteToSiteTunnelResponse) GetKind() BridgeSiteToSiteTunnelKind {
	if o == nil {
		var ret BridgeSiteToSiteTunnelKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetKindOk() (*BridgeSiteToSiteTunnelKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetKind(v BridgeSiteToSiteTunnelKind) {
	o.Kind = v
}

// GetRemoteHost returns the RemoteHost field value
func (o *BridgeSiteToSiteTunnelResponse) GetRemoteHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteHost
}

// GetRemoteHostOk returns a tuple with the RemoteHost field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetRemoteHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteHost, true
}

// SetRemoteHost sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetRemoteHost(v string) {
	o.RemoteHost = v
}

// GetRemotePort returns the RemotePort field value
func (o *BridgeSiteToSiteTunnelResponse) GetRemotePort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RemotePort
}

// GetRemotePortOk returns a tuple with the RemotePort field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetRemotePortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemotePort, true
}

// SetRemotePort sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetRemotePort(v int32) {
	o.RemotePort = v
}

// GetAuthSecretRef returns the AuthSecretRef field value
func (o *BridgeSiteToSiteTunnelResponse) GetAuthSecretRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthSecretRef
}

// GetAuthSecretRefOk returns a tuple with the AuthSecretRef field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetAuthSecretRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthSecretRef, true
}

// SetAuthSecretRef sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetAuthSecretRef(v string) {
	o.AuthSecretRef = v
}

// GetAllowedSubnets returns the AllowedSubnets field value
func (o *BridgeSiteToSiteTunnelResponse) GetAllowedSubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedSubnets
}

// GetAllowedSubnetsOk returns a tuple with the AllowedSubnets field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetAllowedSubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedSubnets, true
}

// SetAllowedSubnets sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetAllowedSubnets(v []string) {
	o.AllowedSubnets = v
}

// GetRoutingPolicy returns the RoutingPolicy field value
func (o *BridgeSiteToSiteTunnelResponse) GetRoutingPolicy() BridgeSiteToSiteTunnelRoutingPolicy {
	if o == nil {
		var ret BridgeSiteToSiteTunnelRoutingPolicy
		return ret
	}

	return o.RoutingPolicy
}

// GetRoutingPolicyOk returns a tuple with the RoutingPolicy field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetRoutingPolicyOk() (*BridgeSiteToSiteTunnelRoutingPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingPolicy, true
}

// SetRoutingPolicy sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetRoutingPolicy(v BridgeSiteToSiteTunnelRoutingPolicy) {
	o.RoutingPolicy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BridgeSiteToSiteTunnelResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BridgeSiteToSiteTunnelResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BridgeSiteToSiteTunnelResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BridgeSiteToSiteTunnelResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o BridgeSiteToSiteTunnelResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BridgeSiteToSiteTunnelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["slug"] = o.Slug
	toSerialize["kind"] = o.Kind
	toSerialize["remote_host"] = o.RemoteHost
	toSerialize["remote_port"] = o.RemotePort
	toSerialize["auth_secret_ref"] = o.AuthSecretRef
	toSerialize["allowed_subnets"] = o.AllowedSubnets
	toSerialize["routing_policy"] = o.RoutingPolicy
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BridgeSiteToSiteTunnelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"slug",
		"kind",
		"remote_host",
		"remote_port",
		"auth_secret_ref",
		"allowed_subnets",
		"routing_policy",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBridgeSiteToSiteTunnelResponse := _BridgeSiteToSiteTunnelResponse{}

	err = json.Unmarshal(data, &varBridgeSiteToSiteTunnelResponse)

	if err != nil {
		return err
	}

	*o = BridgeSiteToSiteTunnelResponse(varBridgeSiteToSiteTunnelResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "remote_host")
		delete(additionalProperties, "remote_port")
		delete(additionalProperties, "auth_secret_ref")
		delete(additionalProperties, "allowed_subnets")
		delete(additionalProperties, "routing_policy")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBridgeSiteToSiteTunnelResponse struct {
	value *BridgeSiteToSiteTunnelResponse
	isSet bool
}

func (v NullableBridgeSiteToSiteTunnelResponse) Get() *BridgeSiteToSiteTunnelResponse {
	return v.value
}

func (v *NullableBridgeSiteToSiteTunnelResponse) Set(val *BridgeSiteToSiteTunnelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgeSiteToSiteTunnelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgeSiteToSiteTunnelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgeSiteToSiteTunnelResponse(val *BridgeSiteToSiteTunnelResponse) *NullableBridgeSiteToSiteTunnelResponse {
	return &NullableBridgeSiteToSiteTunnelResponse{value: val, isSet: true}
}

func (v NullableBridgeSiteToSiteTunnelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgeSiteToSiteTunnelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
