/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the DispatchExecutionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DispatchExecutionRequest{}

// DispatchExecutionRequest Body for `POST /v1/projects/{project_id}/executions:dispatch`. It names the action to dispatch, the parameters to pass, and the target set. The target is EXACTLY ONE of a single `node_id` or an opaque label `selector` — supplying both, or neither, is rejected.
type DispatchExecutionRequest struct {
	// Name of the action to dispatch.
	Action string `json:"action"`
	// Kind of action to dispatch (`builtin` or `hook`). Defaults to `builtin` when omitted.
	Type *ActionKind `json:"type,omitempty"`
	// Opaque JSON parameter document passed verbatim to the action.
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// Per-dispatch execution timeout in whole seconds. A background reconciler times out an invocation whose Node never reports a terminal result within this window.
	TimeoutSeconds *int32 `json:"timeout_seconds,omitempty"`
	// Opaque label selector resolving the target cohort. Supply EXACTLY ONE of `selector` or `node_id`; supplying both, or neither, is rejected.
	Selector *string `json:"selector,omitempty"`
	// Identifier of a single target Node (UUIDv7). Supply EXACTLY ONE of `node_id` or `selector`; supplying both, or neither, is rejected.
	NodeId               *string `json:"node_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DispatchExecutionRequest DispatchExecutionRequest

// NewDispatchExecutionRequest instantiates a new DispatchExecutionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDispatchExecutionRequest(action string) *DispatchExecutionRequest {
	this := DispatchExecutionRequest{}
	this.Action = action
	return &this
}

// NewDispatchExecutionRequestWithDefaults instantiates a new DispatchExecutionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDispatchExecutionRequestWithDefaults() *DispatchExecutionRequest {
	this := DispatchExecutionRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *DispatchExecutionRequest) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *DispatchExecutionRequest) SetAction(v string) {
	o.Action = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DispatchExecutionRequest) GetType() ActionKind {
	if o == nil || IsNil(o.Type) {
		var ret ActionKind
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetTypeOk() (*ActionKind, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DispatchExecutionRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given ActionKind and assigns it to the Type field.
func (o *DispatchExecutionRequest) SetType(v ActionKind) {
	o.Type = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *DispatchExecutionRequest) GetParameters() map[string]interface{} {
	if o == nil || IsNil(o.Parameters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetParametersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return map[string]interface{}{}, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *DispatchExecutionRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *DispatchExecutionRequest) SetParameters(v map[string]interface{}) {
	o.Parameters = v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *DispatchExecutionRequest) GetTimeoutSeconds() int32 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *DispatchExecutionRequest) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given int32 and assigns it to the TimeoutSeconds field.
func (o *DispatchExecutionRequest) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *DispatchExecutionRequest) GetSelector() string {
	if o == nil || IsNil(o.Selector) {
		var ret string
		return ret
	}
	return *o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetSelectorOk() (*string, bool) {
	if o == nil || IsNil(o.Selector) {
		return nil, false
	}
	return o.Selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *DispatchExecutionRequest) HasSelector() bool {
	if o != nil && !IsNil(o.Selector) {
		return true
	}

	return false
}

// SetSelector gets a reference to the given string and assigns it to the Selector field.
func (o *DispatchExecutionRequest) SetSelector(v string) {
	o.Selector = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *DispatchExecutionRequest) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DispatchExecutionRequest) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *DispatchExecutionRequest) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *DispatchExecutionRequest) SetNodeId(v string) {
	o.NodeId = &v
}

func (o DispatchExecutionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DispatchExecutionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Selector) {
		toSerialize["selector"] = o.Selector
	}
	if !IsNil(o.NodeId) {
		toSerialize["node_id"] = o.NodeId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DispatchExecutionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDispatchExecutionRequest := _DispatchExecutionRequest{}

	err = json.Unmarshal(data, &varDispatchExecutionRequest)

	if err != nil {
		return err
	}

	*o = DispatchExecutionRequest(varDispatchExecutionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "type")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "timeout_seconds")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "node_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDispatchExecutionRequest struct {
	value *DispatchExecutionRequest
	isSet bool
}

func (v NullableDispatchExecutionRequest) Get() *DispatchExecutionRequest {
	return v.value
}

func (v *NullableDispatchExecutionRequest) Set(val *DispatchExecutionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDispatchExecutionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDispatchExecutionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDispatchExecutionRequest(val *DispatchExecutionRequest) *NullableDispatchExecutionRequest {
	return &NullableDispatchExecutionRequest{value: val, isSet: true}
}

func (v NullableDispatchExecutionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDispatchExecutionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
