/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// BlueprintParameterDefault - Optional default value applied when a non-required parameter is omitted. Present only when the parameter declares one; its JSON type matches `type`. Absent for required parameters and for optional parameters with no declared default.
type BlueprintParameterDefault struct {
	Bool   *bool
	Int32  *int32
	String *string
}

// boolAsBlueprintParameterDefault is a convenience function that returns bool wrapped in BlueprintParameterDefault
func BoolAsBlueprintParameterDefault(v *bool) BlueprintParameterDefault {
	return BlueprintParameterDefault{
		Bool: v,
	}
}

// int32AsBlueprintParameterDefault is a convenience function that returns int32 wrapped in BlueprintParameterDefault
func Int32AsBlueprintParameterDefault(v *int32) BlueprintParameterDefault {
	return BlueprintParameterDefault{
		Int32: v,
	}
}

// stringAsBlueprintParameterDefault is a convenience function that returns string wrapped in BlueprintParameterDefault
func StringAsBlueprintParameterDefault(v *string) BlueprintParameterDefault {
	return BlueprintParameterDefault{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BlueprintParameterDefault) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = json.Unmarshal(data, &dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			match++
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Int32
	err = json.Unmarshal(data, &dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BlueprintParameterDefault)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BlueprintParameterDefault)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BlueprintParameterDefault) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BlueprintParameterDefault) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BlueprintParameterDefault) GetActualInstanceValue() interface{} {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableBlueprintParameterDefault struct {
	value *BlueprintParameterDefault
	isSet bool
}

func (v NullableBlueprintParameterDefault) Get() *BlueprintParameterDefault {
	return v.value
}

func (v *NullableBlueprintParameterDefault) Set(val *BlueprintParameterDefault) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintParameterDefault) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintParameterDefault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintParameterDefault(val *BlueprintParameterDefault) *NullableBlueprintParameterDefault {
	return &NullableBlueprintParameterDefault{value: val, isSet: true}
}

func (v NullableBlueprintParameterDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintParameterDefault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
