/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SessionActivitySSH type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionActivitySSH{}

// SessionActivitySSH Per-command SSH activity row a Node posts for an `ssh` session.
type SessionActivitySSH struct {
	// The command the session executed, captured as raw text bounded at 1 KiB.
	Command string `json:"command"`
	// Process exit code the command reported, when settled.
	ExitCode *int32 `json:"exit_code,omitempty"`
	// Timestamp the command started (UTC).
	StartedAt *time.Time `json:"started_at,omitempty"`
	// Timestamp the command completed (UTC), when settled.
	CompletedAt          *time.Time `json:"completed_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SessionActivitySSH SessionActivitySSH

// NewSessionActivitySSH instantiates a new SessionActivitySSH object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionActivitySSH(command string) *SessionActivitySSH {
	this := SessionActivitySSH{}
	this.Command = command
	return &this
}

// NewSessionActivitySSHWithDefaults instantiates a new SessionActivitySSH object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionActivitySSHWithDefaults() *SessionActivitySSH {
	this := SessionActivitySSH{}
	return &this
}

// GetCommand returns the Command field value
func (o *SessionActivitySSH) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *SessionActivitySSH) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *SessionActivitySSH) SetCommand(v string) {
	o.Command = v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *SessionActivitySSH) GetExitCode() int32 {
	if o == nil || IsNil(o.ExitCode) {
		var ret int32
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivitySSH) GetExitCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.ExitCode) {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *SessionActivitySSH) HasExitCode() bool {
	if o != nil && !IsNil(o.ExitCode) {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given int32 and assigns it to the ExitCode field.
func (o *SessionActivitySSH) SetExitCode(v int32) {
	o.ExitCode = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *SessionActivitySSH) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivitySSH) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *SessionActivitySSH) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *SessionActivitySSH) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise.
func (o *SessionActivitySSH) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionActivitySSH) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletedAt) {
		return nil, false
	}
	return o.CompletedAt, true
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *SessionActivitySSH) HasCompletedAt() bool {
	if o != nil && !IsNil(o.CompletedAt) {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given time.Time and assigns it to the CompletedAt field.
func (o *SessionActivitySSH) SetCompletedAt(v time.Time) {
	o.CompletedAt = &v
}

func (o SessionActivitySSH) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionActivitySSH) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	if !IsNil(o.ExitCode) {
		toSerialize["exit_code"] = o.ExitCode
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.CompletedAt) {
		toSerialize["completed_at"] = o.CompletedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SessionActivitySSH) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionActivitySSH := _SessionActivitySSH{}

	err = json.Unmarshal(data, &varSessionActivitySSH)

	if err != nil {
		return err
	}

	*o = SessionActivitySSH(varSessionActivitySSH)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "command")
		delete(additionalProperties, "exit_code")
		delete(additionalProperties, "started_at")
		delete(additionalProperties, "completed_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSessionActivitySSH struct {
	value *SessionActivitySSH
	isSet bool
}

func (v NullableSessionActivitySSH) Get() *SessionActivitySSH {
	return v.value
}

func (v *NullableSessionActivitySSH) Set(val *SessionActivitySSH) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionActivitySSH) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionActivitySSH) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionActivitySSH(val *SessionActivitySSH) *NullableSessionActivitySSH {
	return &NullableSessionActivitySSH{value: val, isSet: true}
}

func (v NullableSessionActivitySSH) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionActivitySSH) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
