/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
)

// checks if the ImportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImportRequest{}

// ImportRequest Body for `POST /v1/blueprint-catalogs/{id}/import`. Supply exactly one of `slugs` (a non-empty subset to import) or `all: true` (import every Blueprint the source offers). Supplying neither, both, or an empty `slugs` array surfaces as `400 invalid_import_request`.
type ImportRequest struct {
	// The subset of offered Blueprint slugs to import. Mutually exclusive with `all`; must be non-empty when present and may carry at most 256 entries — the server caps the per-request import subset so one call cannot fan out into an unbounded number of upstream registry round-trips.
	Slugs []string `json:"slugs,omitempty"`
	// Import every Blueprint the source offers. Mutually exclusive with `slugs`.
	All                  *bool `json:"all,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ImportRequest ImportRequest

// NewImportRequest instantiates a new ImportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportRequest() *ImportRequest {
	this := ImportRequest{}
	return &this
}

// NewImportRequestWithDefaults instantiates a new ImportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportRequestWithDefaults() *ImportRequest {
	this := ImportRequest{}
	return &this
}

// GetSlugs returns the Slugs field value if set, zero value otherwise.
func (o *ImportRequest) GetSlugs() []string {
	if o == nil || IsNil(o.Slugs) {
		var ret []string
		return ret
	}
	return o.Slugs
}

// GetSlugsOk returns a tuple with the Slugs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRequest) GetSlugsOk() ([]string, bool) {
	if o == nil || IsNil(o.Slugs) {
		return nil, false
	}
	return o.Slugs, true
}

// HasSlugs returns a boolean if a field has been set.
func (o *ImportRequest) HasSlugs() bool {
	if o != nil && !IsNil(o.Slugs) {
		return true
	}

	return false
}

// SetSlugs gets a reference to the given []string and assigns it to the Slugs field.
func (o *ImportRequest) SetSlugs(v []string) {
	o.Slugs = v
}

// GetAll returns the All field value if set, zero value otherwise.
func (o *ImportRequest) GetAll() bool {
	if o == nil || IsNil(o.All) {
		var ret bool
		return ret
	}
	return *o.All
}

// GetAllOk returns a tuple with the All field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportRequest) GetAllOk() (*bool, bool) {
	if o == nil || IsNil(o.All) {
		return nil, false
	}
	return o.All, true
}

// HasAll returns a boolean if a field has been set.
func (o *ImportRequest) HasAll() bool {
	if o != nil && !IsNil(o.All) {
		return true
	}

	return false
}

// SetAll gets a reference to the given bool and assigns it to the All field.
func (o *ImportRequest) SetAll(v bool) {
	o.All = &v
}

func (o ImportRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Slugs) {
		toSerialize["slugs"] = o.Slugs
	}
	if !IsNil(o.All) {
		toSerialize["all"] = o.All
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ImportRequest) UnmarshalJSON(data []byte) (err error) {
	varImportRequest := _ImportRequest{}

	err = json.Unmarshal(data, &varImportRequest)

	if err != nil {
		return err
	}

	*o = ImportRequest(varImportRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "slugs")
		delete(additionalProperties, "all")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableImportRequest struct {
	value *ImportRequest
	isSet bool
}

func (v NullableImportRequest) Get() *ImportRequest {
	return v.value
}

func (v *NullableImportRequest) Set(val *ImportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableImportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableImportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportRequest(val *ImportRequest) *NullableImportRequest {
	return &NullableImportRequest{value: val, isSet: true}
}

func (v NullableImportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
