/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the CredentialList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialList{}

// CredentialList Page of credentials returned by `GET /v1/projects/{id}/credentials`. The window is computed by the persistence layer in creation order; per-row visibility is layered on top so the `items` array is the subset the caller is authorised to see.
type CredentialList struct {
	// Credentials in the current page.
	Items []CredentialResponse `json:"items"`
	// Continuation token for the next page. `null` or omitted when the iteration has reached end-of-stream. The encoding is HMAC-signed by the server so a tampered cursor surfaces as `400` on the next call.
	NextCursor           *string `json:"next_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CredentialList CredentialList

// NewCredentialList instantiates a new CredentialList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialList(items []CredentialResponse) *CredentialList {
	this := CredentialList{}
	this.Items = items
	return &this
}

// NewCredentialListWithDefaults instantiates a new CredentialList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialListWithDefaults() *CredentialList {
	this := CredentialList{}
	return &this
}

// GetItems returns the Items field value
func (o *CredentialList) GetItems() []CredentialResponse {
	if o == nil {
		var ret []CredentialResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CredentialList) GetItemsOk() ([]CredentialResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *CredentialList) SetItems(v []CredentialResponse) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CredentialList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialList) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CredentialList) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CredentialList) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o CredentialList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CredentialList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialList := _CredentialList{}

	err = json.Unmarshal(data, &varCredentialList)

	if err != nil {
		return err
	}

	*o = CredentialList(varCredentialList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "next_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCredentialList struct {
	value *CredentialList
	isSet bool
}

func (v NullableCredentialList) Get() *CredentialList {
	return v.value
}

func (v *NullableCredentialList) Set(val *CredentialList) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialList) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialList(val *CredentialList) *NullableCredentialList {
	return &NullableCredentialList{value: val, isSet: true}
}

func (v NullableCredentialList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
