/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// EndpointRequestNatType Agent-classified NAT traversal posture. The handler forwards the value verbatim to the Peer aggregate; the controller correlates the value with the per-Domain bridge view in later stories. `unknown` is permitted for agents that have not yet completed STUN probing.
type EndpointRequestNatType string

// List of EndpointRequest_nat_type
const (
	ENDPOINTREQUESTNATTYPE_FULL_CONE                EndpointRequestNatType = "full_cone"
	ENDPOINTREQUESTNATTYPE_RESTRICTED               EndpointRequestNatType = "restricted"
	ENDPOINTREQUESTNATTYPE_PORT_RESTRICTED          EndpointRequestNatType = "port_restricted"
	ENDPOINTREQUESTNATTYPE_SYMMETRIC                EndpointRequestNatType = "symmetric"
	ENDPOINTREQUESTNATTYPE_UNKNOWN                  EndpointRequestNatType = "unknown"
	ENDPOINTREQUESTNATTYPE_UNKNOWN_DEFAULT_OPEN_API EndpointRequestNatType = "unknown_default_open_api"
)

// All allowed values of EndpointRequestNatType enum
var AllowedEndpointRequestNatTypeEnumValues = []EndpointRequestNatType{
	"full_cone",
	"restricted",
	"port_restricted",
	"symmetric",
	"unknown",
	"unknown_default_open_api",
}

func (v *EndpointRequestNatType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EndpointRequestNatType(value)
	for _, existing := range AllowedEndpointRequestNatTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = ENDPOINTREQUESTNATTYPE_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewEndpointRequestNatTypeFromValue returns a pointer to a valid EndpointRequestNatType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEndpointRequestNatTypeFromValue(v string) (*EndpointRequestNatType, error) {
	ev := EndpointRequestNatType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EndpointRequestNatType: valid values are %v", v, AllowedEndpointRequestNatTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EndpointRequestNatType) IsValid() bool {
	for _, existing := range AllowedEndpointRequestNatTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EndpointRequest_nat_type value
func (v EndpointRequestNatType) Ptr() *EndpointRequestNatType {
	return &v
}

type NullableEndpointRequestNatType struct {
	value *EndpointRequestNatType
	isSet bool
}

func (v NullableEndpointRequestNatType) Get() *EndpointRequestNatType {
	return v.value
}

func (v *NullableEndpointRequestNatType) Set(val *EndpointRequestNatType) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointRequestNatType) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointRequestNatType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointRequestNatType(val *EndpointRequestNatType) *NullableEndpointRequestNatType {
	return &NullableEndpointRequestNatType{value: val, isSet: true}
}

func (v NullableEndpointRequestNatType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointRequestNatType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
