/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProviderBundleVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBundleVersion{}

// ProviderBundleVersion One published declaration of a provider bundle: the package set and the ProviderConfig apiVersion frozen under one version number. The item shape of `ProviderBundleVersionList`. A version is immutable once published, so a Cloud pinned to it resolves the same declaration whatever the bundle declares now.
type ProviderBundleVersion struct {
	// The content version number. Numbering starts at 1 and each content patch on the bundle publishes the next one. This is the value a Cloud carries as `provider_bundle_version`.
	Version int64 `json:"version"`
	// The Crossplane provider packages this version declares, rendered in canonical source-ascending order.
	ProviderPackages []CloudProviderPackage `json:"provider_packages"`
	// The `<group>/<version>` every package of this version serves its ProviderConfig under (e.g. `aws.m.upbound.io/v1beta1`).
	ProviderConfigApiVersion string `json:"provider_config_api_version" validate:"regexp=^[a-z0-9]([a-z0-9.-]*[a-z0-9])?\\/v[0-9]+((alpha|beta)[0-9]+)?$"`
	// The subject that published the version. Empty for the versions the schema migration backfilled from the bundles that existed before the history was recorded — there is no publishing principal to attribute those to.
	CreatedBy string `json:"created_by"`
	// Publication timestamp of this version (UTC).
	CreatedAt            time.Time `json:"created_at"`
	AdditionalProperties map[string]interface{}
}

type _ProviderBundleVersion ProviderBundleVersion

// NewProviderBundleVersion instantiates a new ProviderBundleVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBundleVersion(version int64, providerPackages []CloudProviderPackage, providerConfigApiVersion string, createdBy string, createdAt time.Time) *ProviderBundleVersion {
	this := ProviderBundleVersion{}
	this.Version = version
	this.ProviderPackages = providerPackages
	this.ProviderConfigApiVersion = providerConfigApiVersion
	this.CreatedBy = createdBy
	this.CreatedAt = createdAt
	return &this
}

// NewProviderBundleVersionWithDefaults instantiates a new ProviderBundleVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBundleVersionWithDefaults() *ProviderBundleVersion {
	this := ProviderBundleVersion{}
	return &this
}

// GetVersion returns the Version field value
func (o *ProviderBundleVersion) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleVersion) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ProviderBundleVersion) SetVersion(v int64) {
	o.Version = v
}

// GetProviderPackages returns the ProviderPackages field value
func (o *ProviderBundleVersion) GetProviderPackages() []CloudProviderPackage {
	if o == nil {
		var ret []CloudProviderPackage
		return ret
	}

	return o.ProviderPackages
}

// GetProviderPackagesOk returns a tuple with the ProviderPackages field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleVersion) GetProviderPackagesOk() ([]CloudProviderPackage, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderPackages, true
}

// SetProviderPackages sets field value
func (o *ProviderBundleVersion) SetProviderPackages(v []CloudProviderPackage) {
	o.ProviderPackages = v
}

// GetProviderConfigApiVersion returns the ProviderConfigApiVersion field value
func (o *ProviderBundleVersion) GetProviderConfigApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderConfigApiVersion
}

// GetProviderConfigApiVersionOk returns a tuple with the ProviderConfigApiVersion field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleVersion) GetProviderConfigApiVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderConfigApiVersion, true
}

// SetProviderConfigApiVersion sets field value
func (o *ProviderBundleVersion) SetProviderConfigApiVersion(v string) {
	o.ProviderConfigApiVersion = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ProviderBundleVersion) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleVersion) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ProviderBundleVersion) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ProviderBundleVersion) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ProviderBundleVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ProviderBundleVersion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBundleVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["provider_packages"] = o.ProviderPackages
	toSerialize["provider_config_api_version"] = o.ProviderConfigApiVersion
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["created_at"] = o.CreatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProviderBundleVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"provider_packages",
		"provider_config_api_version",
		"created_by",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderBundleVersion := _ProviderBundleVersion{}

	err = json.Unmarshal(data, &varProviderBundleVersion)

	if err != nil {
		return err
	}

	*o = ProviderBundleVersion(varProviderBundleVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "provider_packages")
		delete(additionalProperties, "provider_config_api_version")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "created_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProviderBundleVersion struct {
	value *ProviderBundleVersion
	isSet bool
}

func (v NullableProviderBundleVersion) Get() *ProviderBundleVersion {
	return v.value
}

func (v *NullableProviderBundleVersion) Set(val *ProviderBundleVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBundleVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBundleVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBundleVersion(val *ProviderBundleVersion) *NullableProviderBundleVersion {
	return &NullableProviderBundleVersion{value: val, isSet: true}
}

func (v NullableProviderBundleVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBundleVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
