/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the ProviderBundleCloudRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderBundleCloudRef{}

// ProviderBundleCloudRef Reference to one Cloud that takes its provider configuration from a provider bundle. The item shape of `ProviderBundleCloudList`. The slug and the display name travel alongside the id for the reason `provider_bundle_slug` travels alongside `provider_bundle_id` on `CloudResponse`: the client renders the row without a second round-trip per Cloud.
type ProviderBundleCloudRef struct {
	// Identifier of the referencing Cloud (UUIDv7).
	CloudId string `json:"cloud_id"`
	// Kebab-case URL handle of the referencing Cloud.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// Human-readable name of the referencing Cloud.
	DisplayName string `json:"display_name"`
	// The content version of the bundle this Cloud pins. Rows on one roster page may name different versions: a bundle patch publishes a new version and moves no Cloud, so each Cloud keeps the declaration it was last pinned to until a Cloud write moves that pin.
	ProviderBundleVersion int64 `json:"provider_bundle_version"`
	AdditionalProperties  map[string]interface{}
}

type _ProviderBundleCloudRef ProviderBundleCloudRef

// NewProviderBundleCloudRef instantiates a new ProviderBundleCloudRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderBundleCloudRef(cloudId string, slug string, displayName string, providerBundleVersion int64) *ProviderBundleCloudRef {
	this := ProviderBundleCloudRef{}
	this.CloudId = cloudId
	this.Slug = slug
	this.DisplayName = displayName
	this.ProviderBundleVersion = providerBundleVersion
	return &this
}

// NewProviderBundleCloudRefWithDefaults instantiates a new ProviderBundleCloudRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderBundleCloudRefWithDefaults() *ProviderBundleCloudRef {
	this := ProviderBundleCloudRef{}
	return &this
}

// GetCloudId returns the CloudId field value
func (o *ProviderBundleCloudRef) GetCloudId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudId
}

// GetCloudIdOk returns a tuple with the CloudId field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleCloudRef) GetCloudIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudId, true
}

// SetCloudId sets field value
func (o *ProviderBundleCloudRef) SetCloudId(v string) {
	o.CloudId = v
}

// GetSlug returns the Slug field value
func (o *ProviderBundleCloudRef) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleCloudRef) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *ProviderBundleCloudRef) SetSlug(v string) {
	o.Slug = v
}

// GetDisplayName returns the DisplayName field value
func (o *ProviderBundleCloudRef) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleCloudRef) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ProviderBundleCloudRef) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetProviderBundleVersion returns the ProviderBundleVersion field value
func (o *ProviderBundleCloudRef) GetProviderBundleVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProviderBundleVersion
}

// GetProviderBundleVersionOk returns a tuple with the ProviderBundleVersion field value
// and a boolean to check if the value has been set.
func (o *ProviderBundleCloudRef) GetProviderBundleVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderBundleVersion, true
}

// SetProviderBundleVersion sets field value
func (o *ProviderBundleCloudRef) SetProviderBundleVersion(v int64) {
	o.ProviderBundleVersion = v
}

func (o ProviderBundleCloudRef) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderBundleCloudRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_id"] = o.CloudId
	toSerialize["slug"] = o.Slug
	toSerialize["display_name"] = o.DisplayName
	toSerialize["provider_bundle_version"] = o.ProviderBundleVersion

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProviderBundleCloudRef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloud_id",
		"slug",
		"display_name",
		"provider_bundle_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProviderBundleCloudRef := _ProviderBundleCloudRef{}

	err = json.Unmarshal(data, &varProviderBundleCloudRef)

	if err != nil {
		return err
	}

	*o = ProviderBundleCloudRef(varProviderBundleCloudRef)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cloud_id")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "provider_bundle_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProviderBundleCloudRef struct {
	value *ProviderBundleCloudRef
	isSet bool
}

func (v NullableProviderBundleCloudRef) Get() *ProviderBundleCloudRef {
	return v.value
}

func (v *NullableProviderBundleCloudRef) Set(val *ProviderBundleCloudRef) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderBundleCloudRef) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderBundleCloudRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderBundleCloudRef(val *ProviderBundleCloudRef) *NullableProviderBundleCloudRef {
	return &NullableProviderBundleCloudRef{value: val, isSet: true}
}

func (v NullableProviderBundleCloudRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderBundleCloudRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
