/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CredentialAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialAssignmentRequest{}

// CredentialAssignmentRequest Body for `POST /v1/projects/{id}/credential-assignments`. Names the Cloud Credential to bind to the Project.
type CredentialAssignmentRequest struct {
	// Identifier of the Cloud Credential to bind. Must be a non-zero UUID — a malformed value is rejected with `400 invalid_cloud_credential_id`.
	CloudCredentialId string `json:"cloud_credential_id"`
}

type _CredentialAssignmentRequest CredentialAssignmentRequest

// NewCredentialAssignmentRequest instantiates a new CredentialAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialAssignmentRequest(cloudCredentialId string) *CredentialAssignmentRequest {
	this := CredentialAssignmentRequest{}
	this.CloudCredentialId = cloudCredentialId
	return &this
}

// NewCredentialAssignmentRequestWithDefaults instantiates a new CredentialAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialAssignmentRequestWithDefaults() *CredentialAssignmentRequest {
	this := CredentialAssignmentRequest{}
	return &this
}

// GetCloudCredentialId returns the CloudCredentialId field value
func (o *CredentialAssignmentRequest) GetCloudCredentialId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudCredentialId
}

// GetCloudCredentialIdOk returns a tuple with the CloudCredentialId field value
// and a boolean to check if the value has been set.
func (o *CredentialAssignmentRequest) GetCloudCredentialIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudCredentialId, true
}

// SetCloudCredentialId sets field value
func (o *CredentialAssignmentRequest) SetCloudCredentialId(v string) {
	o.CloudCredentialId = v
}

func (o CredentialAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_credential_id"] = o.CloudCredentialId
	return toSerialize, nil
}

func (o *CredentialAssignmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloud_credential_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialAssignmentRequest := _CredentialAssignmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialAssignmentRequest)

	if err != nil {
		return err
	}

	*o = CredentialAssignmentRequest(varCredentialAssignmentRequest)

	return err
}

type NullableCredentialAssignmentRequest struct {
	value *CredentialAssignmentRequest
	isSet bool
}

func (v NullableCredentialAssignmentRequest) Get() *CredentialAssignmentRequest {
	return v.value
}

func (v *NullableCredentialAssignmentRequest) Set(val *CredentialAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialAssignmentRequest(val *CredentialAssignmentRequest) *NullableCredentialAssignmentRequest {
	return &NullableCredentialAssignmentRequest{value: val, isSet: true}
}

func (v NullableCredentialAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
