/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the PlexdArtifactRefList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlexdArtifactRefList{}

// PlexdArtifactRefList Page of indexed plexd releases returned by `ListPlexdArtifacts`.
type PlexdArtifactRefList struct {
	// Indexed plexd releases in the current page.
	Items []PlexdArtifactRef `json:"items"`
	// Continuation token for the next page. `null` or omitted when the iteration has reached end-of-stream. The encoding is HMAC-signed so a tampered cursor surfaces as `400` on the next call.
	NextCursor           *string `json:"next_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PlexdArtifactRefList PlexdArtifactRefList

// NewPlexdArtifactRefList instantiates a new PlexdArtifactRefList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlexdArtifactRefList(items []PlexdArtifactRef) *PlexdArtifactRefList {
	this := PlexdArtifactRefList{}
	this.Items = items
	return &this
}

// NewPlexdArtifactRefListWithDefaults instantiates a new PlexdArtifactRefList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlexdArtifactRefListWithDefaults() *PlexdArtifactRefList {
	this := PlexdArtifactRefList{}
	return &this
}

// GetItems returns the Items field value
func (o *PlexdArtifactRefList) GetItems() []PlexdArtifactRef {
	if o == nil {
		var ret []PlexdArtifactRef
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PlexdArtifactRefList) GetItemsOk() ([]PlexdArtifactRef, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PlexdArtifactRefList) SetItems(v []PlexdArtifactRef) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *PlexdArtifactRefList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlexdArtifactRefList) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *PlexdArtifactRefList) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *PlexdArtifactRefList) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o PlexdArtifactRefList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlexdArtifactRefList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlexdArtifactRefList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlexdArtifactRefList := _PlexdArtifactRefList{}

	err = json.Unmarshal(data, &varPlexdArtifactRefList)

	if err != nil {
		return err
	}

	*o = PlexdArtifactRefList(varPlexdArtifactRefList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "next_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlexdArtifactRefList struct {
	value *PlexdArtifactRefList
	isSet bool
}

func (v NullablePlexdArtifactRefList) Get() *PlexdArtifactRefList {
	return v.value
}

func (v *NullablePlexdArtifactRefList) Set(val *PlexdArtifactRefList) {
	v.value = val
	v.isSet = true
}

func (v NullablePlexdArtifactRefList) IsSet() bool {
	return v.isSet
}

func (v *NullablePlexdArtifactRefList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlexdArtifactRefList(val *PlexdArtifactRefList) *NullablePlexdArtifactRefList {
	return &NullablePlexdArtifactRefList{value: val, isSet: true}
}

func (v NullablePlexdArtifactRefList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlexdArtifactRefList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
