/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the NodeStatePeer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeStatePeer{}

// NodeStatePeer Minimal projection of a Domain peer that the addressed Node needs in order to program its WireGuard table. The shape is deliberately narrow and mirrors `RegisterPeer` so the reconciliation pull and the registration bootstrap converge on the same wire contract.
type NodeStatePeer struct {
	// Peer's Node identifier. Plexd's reconcile loop keys peers by id.
	NodeId string `json:"node_id"`
	// Peer's allocator-assigned mesh address. Plexd programs the WireGuard endpoint from this field.
	MeshIp string `json:"mesh_ip"`
	// Peer's WireGuard public key, base64-encoded with standard padding.
	PublicKey string `json:"public_key" validate:"regexp=^[A-Za-z0-9+\\/]{43}=$"`
	// Canonical bridge `host:port` that plexd programs as a NAT-traversal relay when direct peer-to-peer connectivity is unavailable. Empty or absent means no bridge is currently assigned for this peer. Format: `<inet-or-hostname>:<port>`.
	FallbackEndpoint     *string `json:"fallback_endpoint,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NodeStatePeer NodeStatePeer

// NewNodeStatePeer instantiates a new NodeStatePeer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeStatePeer(nodeId string, meshIp string, publicKey string) *NodeStatePeer {
	this := NodeStatePeer{}
	this.NodeId = nodeId
	this.MeshIp = meshIp
	this.PublicKey = publicKey
	return &this
}

// NewNodeStatePeerWithDefaults instantiates a new NodeStatePeer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeStatePeerWithDefaults() *NodeStatePeer {
	this := NodeStatePeer{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *NodeStatePeer) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *NodeStatePeer) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *NodeStatePeer) SetNodeId(v string) {
	o.NodeId = v
}

// GetMeshIp returns the MeshIp field value
func (o *NodeStatePeer) GetMeshIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeshIp
}

// GetMeshIpOk returns a tuple with the MeshIp field value
// and a boolean to check if the value has been set.
func (o *NodeStatePeer) GetMeshIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeshIp, true
}

// SetMeshIp sets field value
func (o *NodeStatePeer) SetMeshIp(v string) {
	o.MeshIp = v
}

// GetPublicKey returns the PublicKey field value
func (o *NodeStatePeer) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *NodeStatePeer) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *NodeStatePeer) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetFallbackEndpoint returns the FallbackEndpoint field value if set, zero value otherwise.
func (o *NodeStatePeer) GetFallbackEndpoint() string {
	if o == nil || IsNil(o.FallbackEndpoint) {
		var ret string
		return ret
	}
	return *o.FallbackEndpoint
}

// GetFallbackEndpointOk returns a tuple with the FallbackEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeStatePeer) GetFallbackEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.FallbackEndpoint) {
		return nil, false
	}
	return o.FallbackEndpoint, true
}

// HasFallbackEndpoint returns a boolean if a field has been set.
func (o *NodeStatePeer) HasFallbackEndpoint() bool {
	if o != nil && !IsNil(o.FallbackEndpoint) {
		return true
	}

	return false
}

// SetFallbackEndpoint gets a reference to the given string and assigns it to the FallbackEndpoint field.
func (o *NodeStatePeer) SetFallbackEndpoint(v string) {
	o.FallbackEndpoint = &v
}

func (o NodeStatePeer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeStatePeer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	toSerialize["mesh_ip"] = o.MeshIp
	toSerialize["public_key"] = o.PublicKey
	if !IsNil(o.FallbackEndpoint) {
		toSerialize["fallback_endpoint"] = o.FallbackEndpoint
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NodeStatePeer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"mesh_ip",
		"public_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeStatePeer := _NodeStatePeer{}

	err = json.Unmarshal(data, &varNodeStatePeer)

	if err != nil {
		return err
	}

	*o = NodeStatePeer(varNodeStatePeer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "node_id")
		delete(additionalProperties, "mesh_ip")
		delete(additionalProperties, "public_key")
		delete(additionalProperties, "fallback_endpoint")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNodeStatePeer struct {
	value *NodeStatePeer
	isSet bool
}

func (v NullableNodeStatePeer) Get() *NodeStatePeer {
	return v.value
}

func (v *NullableNodeStatePeer) Set(val *NodeStatePeer) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeStatePeer) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeStatePeer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeStatePeer(val *NodeStatePeer) *NullableNodeStatePeer {
	return &NullableNodeStatePeer{value: val, isSet: true}
}

func (v NullableNodeStatePeer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeStatePeer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
