/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// DeviceApproveResponseStatus Always `approved` on a 200.
type DeviceApproveResponseStatus string

// List of DeviceApproveResponse_status
const (
	DEVICEAPPROVERESPONSESTATUS_APPROVED                 DeviceApproveResponseStatus = "approved"
	DEVICEAPPROVERESPONSESTATUS_UNKNOWN_DEFAULT_OPEN_API DeviceApproveResponseStatus = "unknown_default_open_api"
)

// All allowed values of DeviceApproveResponseStatus enum
var AllowedDeviceApproveResponseStatusEnumValues = []DeviceApproveResponseStatus{
	"approved",
	"unknown_default_open_api",
}

func (v *DeviceApproveResponseStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeviceApproveResponseStatus(value)
	for _, existing := range AllowedDeviceApproveResponseStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = DEVICEAPPROVERESPONSESTATUS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewDeviceApproveResponseStatusFromValue returns a pointer to a valid DeviceApproveResponseStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeviceApproveResponseStatusFromValue(v string) (*DeviceApproveResponseStatus, error) {
	ev := DeviceApproveResponseStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeviceApproveResponseStatus: valid values are %v", v, AllowedDeviceApproveResponseStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeviceApproveResponseStatus) IsValid() bool {
	for _, existing := range AllowedDeviceApproveResponseStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DeviceApproveResponse_status value
func (v DeviceApproveResponseStatus) Ptr() *DeviceApproveResponseStatus {
	return &v
}

type NullableDeviceApproveResponseStatus struct {
	value *DeviceApproveResponseStatus
	isSet bool
}

func (v NullableDeviceApproveResponseStatus) Get() *DeviceApproveResponseStatus {
	return v.value
}

func (v *NullableDeviceApproveResponseStatus) Set(val *DeviceApproveResponseStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceApproveResponseStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceApproveResponseStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceApproveResponseStatus(val *DeviceApproveResponseStatus) *NullableDeviceApproveResponseStatus {
	return &NullableDeviceApproveResponseStatus{value: val, isSet: true}
}

func (v NullableDeviceApproveResponseStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceApproveResponseStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
