/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the BuiltinActionParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuiltinActionParameter{}

// BuiltinActionParameter A single parameter declaration inside a `BuiltinAction`'s `parameters` list.  Every field but `name` is descriptive: plexsphere records what the agent reported and validates nothing against it. In particular `type` is not a closed enum and `required` does not gate dispatch — an execution carrying the wrong parameters is refused by the Node that runs it, which is the only place that knows the current truth. Constraining these here would create a second, staler authority.
type BuiltinActionParameter struct {
	// Parameter identifier as the action expects it in a dispatch's `parameters` object. Non-empty after trimming whitespace; a violation surfaces as 422 `builtin_action_invalid`.
	Name string `json:"name"`
	// Optional agent-reported type name (e.g. `string`, `int`, `duration`). Free-form and recorded verbatim — see the schema description for why it is not an enum.
	Type *string `json:"type,omitempty"`
	// Whether the agent reports the parameter as mandatory. Descriptive only; dispatch is not gated on it.
	Required *bool `json:"required,omitempty"`
	// Optional default value the agent applies when the parameter is omitted, rendered as the agent reported it.
	Default *string `json:"default,omitempty"`
	// Optional human-readable summary of the parameter.
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BuiltinActionParameter BuiltinActionParameter

// NewBuiltinActionParameter instantiates a new BuiltinActionParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuiltinActionParameter(name string) *BuiltinActionParameter {
	this := BuiltinActionParameter{}
	this.Name = name
	var required bool = false
	this.Required = &required
	return &this
}

// NewBuiltinActionParameterWithDefaults instantiates a new BuiltinActionParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuiltinActionParameterWithDefaults() *BuiltinActionParameter {
	this := BuiltinActionParameter{}
	var required bool = false
	this.Required = &required
	return &this
}

// GetName returns the Name field value
func (o *BuiltinActionParameter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BuiltinActionParameter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BuiltinActionParameter) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *BuiltinActionParameter) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltinActionParameter) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *BuiltinActionParameter) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *BuiltinActionParameter) SetType(v string) {
	o.Type = &v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *BuiltinActionParameter) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltinActionParameter) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *BuiltinActionParameter) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *BuiltinActionParameter) SetRequired(v bool) {
	o.Required = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *BuiltinActionParameter) GetDefault() string {
	if o == nil || IsNil(o.Default) {
		var ret string
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltinActionParameter) GetDefaultOk() (*string, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *BuiltinActionParameter) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given string and assigns it to the Default field.
func (o *BuiltinActionParameter) SetDefault(v string) {
	o.Default = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BuiltinActionParameter) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuiltinActionParameter) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BuiltinActionParameter) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BuiltinActionParameter) SetDescription(v string) {
	o.Description = &v
}

func (o BuiltinActionParameter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuiltinActionParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BuiltinActionParameter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuiltinActionParameter := _BuiltinActionParameter{}

	err = json.Unmarshal(data, &varBuiltinActionParameter)

	if err != nil {
		return err
	}

	*o = BuiltinActionParameter(varBuiltinActionParameter)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "required")
		delete(additionalProperties, "default")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBuiltinActionParameter struct {
	value *BuiltinActionParameter
	isSet bool
}

func (v NullableBuiltinActionParameter) Get() *BuiltinActionParameter {
	return v.value
}

func (v *NullableBuiltinActionParameter) Set(val *BuiltinActionParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableBuiltinActionParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableBuiltinActionParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuiltinActionParameter(val *BuiltinActionParameter) *NullableBuiltinActionParameter {
	return &NullableBuiltinActionParameter{value: val, isSet: true}
}

func (v NullableBuiltinActionParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuiltinActionParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
