/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
)

// checks if the SignInRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignInRequest{}

// SignInRequest Body for POST /v1/auth/sign-in. At least one of `domain_id` or `idp_binding_id` must be supplied; the router uses them to resolve the IdP binding against which to begin the flow .
type SignInRequest struct {
	// Domain the user is signing into.
	DomainId *string `json:"domain_id,omitempty"`
	// Explicit IdP binding override within a Domain.
	IdpBindingId *string `json:"idp_binding_id,omitempty"`
	// Post-sign-in redirect target. Must be an allow-listed relative path or absolute URL.
	ReturnTo *string `json:"return_to,omitempty"`
	// Optional OIDC `prompt` parameter forwarded to the IdP (e.g. \"login\", \"consent\").
	Prompt               *string `json:"prompt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SignInRequest SignInRequest

// NewSignInRequest instantiates a new SignInRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignInRequest() *SignInRequest {
	this := SignInRequest{}
	return &this
}

// NewSignInRequestWithDefaults instantiates a new SignInRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignInRequestWithDefaults() *SignInRequest {
	this := SignInRequest{}
	return &this
}

// GetDomainId returns the DomainId field value if set, zero value otherwise.
func (o *SignInRequest) GetDomainId() string {
	if o == nil || IsNil(o.DomainId) {
		var ret string
		return ret
	}
	return *o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetDomainIdOk() (*string, bool) {
	if o == nil || IsNil(o.DomainId) {
		return nil, false
	}
	return o.DomainId, true
}

// HasDomainId returns a boolean if a field has been set.
func (o *SignInRequest) HasDomainId() bool {
	if o != nil && !IsNil(o.DomainId) {
		return true
	}

	return false
}

// SetDomainId gets a reference to the given string and assigns it to the DomainId field.
func (o *SignInRequest) SetDomainId(v string) {
	o.DomainId = &v
}

// GetIdpBindingId returns the IdpBindingId field value if set, zero value otherwise.
func (o *SignInRequest) GetIdpBindingId() string {
	if o == nil || IsNil(o.IdpBindingId) {
		var ret string
		return ret
	}
	return *o.IdpBindingId
}

// GetIdpBindingIdOk returns a tuple with the IdpBindingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetIdpBindingIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdpBindingId) {
		return nil, false
	}
	return o.IdpBindingId, true
}

// HasIdpBindingId returns a boolean if a field has been set.
func (o *SignInRequest) HasIdpBindingId() bool {
	if o != nil && !IsNil(o.IdpBindingId) {
		return true
	}

	return false
}

// SetIdpBindingId gets a reference to the given string and assigns it to the IdpBindingId field.
func (o *SignInRequest) SetIdpBindingId(v string) {
	o.IdpBindingId = &v
}

// GetReturnTo returns the ReturnTo field value if set, zero value otherwise.
func (o *SignInRequest) GetReturnTo() string {
	if o == nil || IsNil(o.ReturnTo) {
		var ret string
		return ret
	}
	return *o.ReturnTo
}

// GetReturnToOk returns a tuple with the ReturnTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetReturnToOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnTo) {
		return nil, false
	}
	return o.ReturnTo, true
}

// HasReturnTo returns a boolean if a field has been set.
func (o *SignInRequest) HasReturnTo() bool {
	if o != nil && !IsNil(o.ReturnTo) {
		return true
	}

	return false
}

// SetReturnTo gets a reference to the given string and assigns it to the ReturnTo field.
func (o *SignInRequest) SetReturnTo(v string) {
	o.ReturnTo = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *SignInRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SignInRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *SignInRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *SignInRequest) SetPrompt(v string) {
	o.Prompt = &v
}

func (o SignInRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignInRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainId) {
		toSerialize["domain_id"] = o.DomainId
	}
	if !IsNil(o.IdpBindingId) {
		toSerialize["idp_binding_id"] = o.IdpBindingId
	}
	if !IsNil(o.ReturnTo) {
		toSerialize["return_to"] = o.ReturnTo
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SignInRequest) UnmarshalJSON(data []byte) (err error) {
	varSignInRequest := _SignInRequest{}

	err = json.Unmarshal(data, &varSignInRequest)

	if err != nil {
		return err
	}

	*o = SignInRequest(varSignInRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain_id")
		delete(additionalProperties, "idp_binding_id")
		delete(additionalProperties, "return_to")
		delete(additionalProperties, "prompt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSignInRequest struct {
	value *SignInRequest
	isSet bool
}

func (v NullableSignInRequest) Get() *SignInRequest {
	return v.value
}

func (v *NullableSignInRequest) Set(val *SignInRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSignInRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSignInRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignInRequest(val *SignInRequest) *NullableSignInRequest {
	return &NullableSignInRequest{value: val, isSet: true}
}

func (v NullableSignInRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignInRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
