/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the SignInResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignInResponse{}

// SignInResponse Response for POST /v1/auth/sign-in. `code_verifier_handle` is an opaque key the server uses to recover the PKCE verifier on the callback; the verifier itself never leaves the backend.
type SignInResponse struct {
	// OIDC authorization URL the caller redirects to.
	AuthorizationUrl string `json:"authorization_url"`
	// Opaque state value correlated on the callback.
	State string `json:"state"`
	// Opaque handle that resolves the PKCE verifier.
	CodeVerifierHandle string `json:"code_verifier_handle"`
	// OIDC nonce passed into the ID token.
	Nonce                string `json:"nonce"`
	AdditionalProperties map[string]interface{}
}

type _SignInResponse SignInResponse

// NewSignInResponse instantiates a new SignInResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignInResponse(authorizationUrl string, state string, codeVerifierHandle string, nonce string) *SignInResponse {
	this := SignInResponse{}
	this.AuthorizationUrl = authorizationUrl
	this.State = state
	this.CodeVerifierHandle = codeVerifierHandle
	this.Nonce = nonce
	return &this
}

// NewSignInResponseWithDefaults instantiates a new SignInResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignInResponseWithDefaults() *SignInResponse {
	this := SignInResponse{}
	return &this
}

// GetAuthorizationUrl returns the AuthorizationUrl field value
func (o *SignInResponse) GetAuthorizationUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizationUrl
}

// GetAuthorizationUrlOk returns a tuple with the AuthorizationUrl field value
// and a boolean to check if the value has been set.
func (o *SignInResponse) GetAuthorizationUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizationUrl, true
}

// SetAuthorizationUrl sets field value
func (o *SignInResponse) SetAuthorizationUrl(v string) {
	o.AuthorizationUrl = v
}

// GetState returns the State field value
func (o *SignInResponse) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *SignInResponse) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *SignInResponse) SetState(v string) {
	o.State = v
}

// GetCodeVerifierHandle returns the CodeVerifierHandle field value
func (o *SignInResponse) GetCodeVerifierHandle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeVerifierHandle
}

// GetCodeVerifierHandleOk returns a tuple with the CodeVerifierHandle field value
// and a boolean to check if the value has been set.
func (o *SignInResponse) GetCodeVerifierHandleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeVerifierHandle, true
}

// SetCodeVerifierHandle sets field value
func (o *SignInResponse) SetCodeVerifierHandle(v string) {
	o.CodeVerifierHandle = v
}

// GetNonce returns the Nonce field value
func (o *SignInResponse) GetNonce() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value
// and a boolean to check if the value has been set.
func (o *SignInResponse) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nonce, true
}

// SetNonce sets field value
func (o *SignInResponse) SetNonce(v string) {
	o.Nonce = v
}

func (o SignInResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignInResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authorization_url"] = o.AuthorizationUrl
	toSerialize["state"] = o.State
	toSerialize["code_verifier_handle"] = o.CodeVerifierHandle
	toSerialize["nonce"] = o.Nonce

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SignInResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authorization_url",
		"state",
		"code_verifier_handle",
		"nonce",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSignInResponse := _SignInResponse{}

	err = json.Unmarshal(data, &varSignInResponse)

	if err != nil {
		return err
	}

	*o = SignInResponse(varSignInResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "authorization_url")
		delete(additionalProperties, "state")
		delete(additionalProperties, "code_verifier_handle")
		delete(additionalProperties, "nonce")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSignInResponse struct {
	value *SignInResponse
	isSet bool
}

func (v NullableSignInResponse) Get() *SignInResponse {
	return v.value
}

func (v *NullableSignInResponse) Set(val *SignInResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSignInResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSignInResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignInResponse(val *SignInResponse) *NullableSignInResponse {
	return &NullableSignInResponse{value: val, isSet: true}
}

func (v NullableSignInResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignInResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
