/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IntegrityViolationAcknowledgeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrityViolationAcknowledgeRequest{}

// IntegrityViolationAcknowledgeRequest Body for `POST /v1/integrity-violations/{id}/acknowledge`. The `reason` is recorded on the triage row as the operator-supplied rationale for moving the violation out of the `open` state.
type IntegrityViolationAcknowledgeRequest struct {
	// Acknowledgement rationale. Non-empty — whitespace-only is rejected with `400 invalid_acknowledge_reason`.
	Reason string `json:"reason"`
}

type _IntegrityViolationAcknowledgeRequest IntegrityViolationAcknowledgeRequest

// NewIntegrityViolationAcknowledgeRequest instantiates a new IntegrityViolationAcknowledgeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrityViolationAcknowledgeRequest(reason string) *IntegrityViolationAcknowledgeRequest {
	this := IntegrityViolationAcknowledgeRequest{}
	this.Reason = reason
	return &this
}

// NewIntegrityViolationAcknowledgeRequestWithDefaults instantiates a new IntegrityViolationAcknowledgeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrityViolationAcknowledgeRequestWithDefaults() *IntegrityViolationAcknowledgeRequest {
	this := IntegrityViolationAcknowledgeRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *IntegrityViolationAcknowledgeRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *IntegrityViolationAcknowledgeRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *IntegrityViolationAcknowledgeRequest) SetReason(v string) {
	o.Reason = v
}

func (o IntegrityViolationAcknowledgeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrityViolationAcknowledgeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	return toSerialize, nil
}

func (o *IntegrityViolationAcknowledgeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntegrityViolationAcknowledgeRequest := _IntegrityViolationAcknowledgeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIntegrityViolationAcknowledgeRequest)

	if err != nil {
		return err
	}

	*o = IntegrityViolationAcknowledgeRequest(varIntegrityViolationAcknowledgeRequest)

	return err
}

type NullableIntegrityViolationAcknowledgeRequest struct {
	value *IntegrityViolationAcknowledgeRequest
	isSet bool
}

func (v NullableIntegrityViolationAcknowledgeRequest) Get() *IntegrityViolationAcknowledgeRequest {
	return v.value
}

func (v *NullableIntegrityViolationAcknowledgeRequest) Set(val *IntegrityViolationAcknowledgeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrityViolationAcknowledgeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrityViolationAcknowledgeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrityViolationAcknowledgeRequest(val *IntegrityViolationAcknowledgeRequest) *NullableIntegrityViolationAcknowledgeRequest {
	return &NullableIntegrityViolationAcknowledgeRequest{value: val, isSet: true}
}

func (v NullableIntegrityViolationAcknowledgeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrityViolationAcknowledgeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
