/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the DomainCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainCreateRequest{}

// DomainCreateRequest Body for `POST /v1/domains`. Field set mirrors the Domain aggregate's `NewDomain` invariants. The handler authorises the call against the platform-level `manage` relation BEFORE invoking the service so an unauthorised caller never produces a `DomainCreated` outbox row.
type DomainCreateRequest struct {
	// Human-readable Domain name. Whitespace-only is rejected.
	Name string `json:"name"`
	// Kebab-case URL handle. The aggregate's `ParseSlug` enforces the same regex; surfacing the pattern here lets the generated client validate before the round-trip.
	Slug string `json:"slug" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// Optional free-form description. Whitespace-only strings are rejected by the aggregate (the operator most likely fat- fingered the field instead of meaning to clear it).
	Description *string `json:"description,omitempty"`
	// Optional region the Domain is pinned to at creation; absent or empty means the Domain is left unpinned. The aggregate's `ParseRegion` enforces the same regex, so surfacing the pattern here lets the generated client validate before the round-trip.
	Region *string `json:"region,omitempty" validate:"regexp=^[a-z0-9]+(-[a-z0-9]+)*$"`
	// Canonical RFC 4632 mesh-IP pool. Cross-Domain non-overlap is enforced by the SQL GIST exclusion constraint and surfaces as `409 mesh_cidr_overlap`.
	MeshCidr             string                    `json:"mesh_cidr"`
	Reachability         *DomainReachabilityPolicy `json:"reachability,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DomainCreateRequest DomainCreateRequest

// NewDomainCreateRequest instantiates a new DomainCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainCreateRequest(name string, slug string, meshCidr string) *DomainCreateRequest {
	this := DomainCreateRequest{}
	this.Name = name
	this.Slug = slug
	this.MeshCidr = meshCidr
	return &this
}

// NewDomainCreateRequestWithDefaults instantiates a new DomainCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainCreateRequestWithDefaults() *DomainCreateRequest {
	this := DomainCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *DomainCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DomainCreateRequest) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *DomainCreateRequest) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *DomainCreateRequest) SetSlug(v string) {
	o.Slug = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DomainCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DomainCreateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DomainCreateRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *DomainCreateRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *DomainCreateRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *DomainCreateRequest) SetRegion(v string) {
	o.Region = &v
}

// GetMeshCidr returns the MeshCidr field value
func (o *DomainCreateRequest) GetMeshCidr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MeshCidr
}

// GetMeshCidrOk returns a tuple with the MeshCidr field value
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetMeshCidrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MeshCidr, true
}

// SetMeshCidr sets field value
func (o *DomainCreateRequest) SetMeshCidr(v string) {
	o.MeshCidr = v
}

// GetReachability returns the Reachability field value if set, zero value otherwise.
func (o *DomainCreateRequest) GetReachability() DomainReachabilityPolicy {
	if o == nil || IsNil(o.Reachability) {
		var ret DomainReachabilityPolicy
		return ret
	}
	return *o.Reachability
}

// GetReachabilityOk returns a tuple with the Reachability field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainCreateRequest) GetReachabilityOk() (*DomainReachabilityPolicy, bool) {
	if o == nil || IsNil(o.Reachability) {
		return nil, false
	}
	return o.Reachability, true
}

// HasReachability returns a boolean if a field has been set.
func (o *DomainCreateRequest) HasReachability() bool {
	if o != nil && !IsNil(o.Reachability) {
		return true
	}

	return false
}

// SetReachability gets a reference to the given DomainReachabilityPolicy and assigns it to the Reachability field.
func (o *DomainCreateRequest) SetReachability(v DomainReachabilityPolicy) {
	o.Reachability = &v
}

func (o DomainCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	toSerialize["mesh_cidr"] = o.MeshCidr
	if !IsNil(o.Reachability) {
		toSerialize["reachability"] = o.Reachability
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DomainCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"slug",
		"mesh_cidr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainCreateRequest := _DomainCreateRequest{}

	err = json.Unmarshal(data, &varDomainCreateRequest)

	if err != nil {
		return err
	}

	*o = DomainCreateRequest(varDomainCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "description")
		delete(additionalProperties, "region")
		delete(additionalProperties, "mesh_cidr")
		delete(additionalProperties, "reachability")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDomainCreateRequest struct {
	value *DomainCreateRequest
	isSet bool
}

func (v NullableDomainCreateRequest) Get() *DomainCreateRequest {
	return v.value
}

func (v *NullableDomainCreateRequest) Set(val *DomainCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainCreateRequest(val *DomainCreateRequest) *NullableDomainCreateRequest {
	return &NullableDomainCreateRequest{value: val, isSet: true}
}

func (v NullableDomainCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
