/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// ServiceFederationKind Credential shape a service identity authenticates with. `oidc_cc` is an OIDC client-credentials access token from the Domain's IdPBinding; `spiffe_svid` is a JWT-SVID from a SPIFFE workload API; `api_token` is a plexsphere-issued bearer bound to the identity. The pin is enforced at sign-in: a credential of a different kind is rejected without inspecting its payload. The three values mirror the plexsphere.service_identities.federation_kind CHECK constraint.
type ServiceFederationKind string

// List of ServiceFederationKind
const (
	SERVICEFEDERATIONKIND_OIDC_CC                  ServiceFederationKind = "oidc_cc"
	SERVICEFEDERATIONKIND_SPIFFE_SVID              ServiceFederationKind = "spiffe_svid"
	SERVICEFEDERATIONKIND_API_TOKEN                ServiceFederationKind = "api_token"
	SERVICEFEDERATIONKIND_UNKNOWN_DEFAULT_OPEN_API ServiceFederationKind = "unknown_default_open_api"
)

// All allowed values of ServiceFederationKind enum
var AllowedServiceFederationKindEnumValues = []ServiceFederationKind{
	"oidc_cc",
	"spiffe_svid",
	"api_token",
	"unknown_default_open_api",
}

func (v *ServiceFederationKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServiceFederationKind(value)
	for _, existing := range AllowedServiceFederationKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SERVICEFEDERATIONKIND_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewServiceFederationKindFromValue returns a pointer to a valid ServiceFederationKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServiceFederationKindFromValue(v string) (*ServiceFederationKind, error) {
	ev := ServiceFederationKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServiceFederationKind: valid values are %v", v, AllowedServiceFederationKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServiceFederationKind) IsValid() bool {
	for _, existing := range AllowedServiceFederationKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ServiceFederationKind value
func (v ServiceFederationKind) Ptr() *ServiceFederationKind {
	return &v
}

type NullableServiceFederationKind struct {
	value *ServiceFederationKind
	isSet bool
}

func (v NullableServiceFederationKind) Get() *ServiceFederationKind {
	return v.value
}

func (v *NullableServiceFederationKind) Set(val *ServiceFederationKind) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceFederationKind) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceFederationKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceFederationKind(val *ServiceFederationKind) *NullableServiceFederationKind {
	return &NullableServiceFederationKind{value: val, isSet: true}
}

func (v NullableServiceFederationKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceFederationKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
