/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the IdPBindingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdPBindingRequest{}

// IdPBindingRequest Body for POST /v1/admin/idp. Field set mirrors the `IdPBinding` aggregate.
type IdPBindingRequest struct {
	// Owning Domain.
	DomainId string `json:"domain_id"`
	// OIDC issuer URL (absolute http/https).
	Issuer string `json:"issuer"`
	// OIDC client identifier.
	ClientId string `json:"client_id"`
	// Opaque reference to the client secret held in the secret store — never the secret value itself.
	ClientSecretRef string `json:"client_secret_ref"`
	// OIDC discovery document URL (absolute http/https).
	DiscoveryUrl string `json:"discovery_url"`
	// Mapping of plexsphere claim name → IdP claim name. An empty map is permitted.
	ClaimMappings map[string]string `json:"claim_mappings,omitempty"`
	// Required OIDC ACR values.
	RequiredAcr []string `json:"required_acr,omitempty"`
	// Required OIDC AMR values.
	RequiredAmr          []string                   `json:"required_amr,omitempty"`
	JitPolicy            IdPBindingRequestJitPolicy `json:"jit_policy"`
	AdditionalProperties map[string]interface{}
}

type _IdPBindingRequest IdPBindingRequest

// NewIdPBindingRequest instantiates a new IdPBindingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdPBindingRequest(domainId string, issuer string, clientId string, clientSecretRef string, discoveryUrl string, jitPolicy IdPBindingRequestJitPolicy) *IdPBindingRequest {
	this := IdPBindingRequest{}
	this.DomainId = domainId
	this.Issuer = issuer
	this.ClientId = clientId
	this.ClientSecretRef = clientSecretRef
	this.DiscoveryUrl = discoveryUrl
	this.JitPolicy = jitPolicy
	return &this
}

// NewIdPBindingRequestWithDefaults instantiates a new IdPBindingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdPBindingRequestWithDefaults() *IdPBindingRequest {
	this := IdPBindingRequest{}
	return &this
}

// GetDomainId returns the DomainId field value
func (o *IdPBindingRequest) GetDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DomainId, true
}

// SetDomainId sets field value
func (o *IdPBindingRequest) SetDomainId(v string) {
	o.DomainId = v
}

// GetIssuer returns the Issuer field value
func (o *IdPBindingRequest) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *IdPBindingRequest) SetIssuer(v string) {
	o.Issuer = v
}

// GetClientId returns the ClientId field value
func (o *IdPBindingRequest) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *IdPBindingRequest) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecretRef returns the ClientSecretRef field value
func (o *IdPBindingRequest) GetClientSecretRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecretRef
}

// GetClientSecretRefOk returns a tuple with the ClientSecretRef field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetClientSecretRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecretRef, true
}

// SetClientSecretRef sets field value
func (o *IdPBindingRequest) SetClientSecretRef(v string) {
	o.ClientSecretRef = v
}

// GetDiscoveryUrl returns the DiscoveryUrl field value
func (o *IdPBindingRequest) GetDiscoveryUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DiscoveryUrl
}

// GetDiscoveryUrlOk returns a tuple with the DiscoveryUrl field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetDiscoveryUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiscoveryUrl, true
}

// SetDiscoveryUrl sets field value
func (o *IdPBindingRequest) SetDiscoveryUrl(v string) {
	o.DiscoveryUrl = v
}

// GetClaimMappings returns the ClaimMappings field value if set, zero value otherwise.
func (o *IdPBindingRequest) GetClaimMappings() map[string]string {
	if o == nil || IsNil(o.ClaimMappings) {
		var ret map[string]string
		return ret
	}
	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetClaimMappingsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.ClaimMappings) {
		return map[string]string{}, false
	}
	return o.ClaimMappings, true
}

// HasClaimMappings returns a boolean if a field has been set.
func (o *IdPBindingRequest) HasClaimMappings() bool {
	if o != nil && !IsNil(o.ClaimMappings) {
		return true
	}

	return false
}

// SetClaimMappings gets a reference to the given map[string]string and assigns it to the ClaimMappings field.
func (o *IdPBindingRequest) SetClaimMappings(v map[string]string) {
	o.ClaimMappings = v
}

// GetRequiredAcr returns the RequiredAcr field value if set, zero value otherwise.
func (o *IdPBindingRequest) GetRequiredAcr() []string {
	if o == nil || IsNil(o.RequiredAcr) {
		var ret []string
		return ret
	}
	return o.RequiredAcr
}

// GetRequiredAcrOk returns a tuple with the RequiredAcr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetRequiredAcrOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredAcr) {
		return nil, false
	}
	return o.RequiredAcr, true
}

// HasRequiredAcr returns a boolean if a field has been set.
func (o *IdPBindingRequest) HasRequiredAcr() bool {
	if o != nil && !IsNil(o.RequiredAcr) {
		return true
	}

	return false
}

// SetRequiredAcr gets a reference to the given []string and assigns it to the RequiredAcr field.
func (o *IdPBindingRequest) SetRequiredAcr(v []string) {
	o.RequiredAcr = v
}

// GetRequiredAmr returns the RequiredAmr field value if set, zero value otherwise.
func (o *IdPBindingRequest) GetRequiredAmr() []string {
	if o == nil || IsNil(o.RequiredAmr) {
		var ret []string
		return ret
	}
	return o.RequiredAmr
}

// GetRequiredAmrOk returns a tuple with the RequiredAmr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetRequiredAmrOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredAmr) {
		return nil, false
	}
	return o.RequiredAmr, true
}

// HasRequiredAmr returns a boolean if a field has been set.
func (o *IdPBindingRequest) HasRequiredAmr() bool {
	if o != nil && !IsNil(o.RequiredAmr) {
		return true
	}

	return false
}

// SetRequiredAmr gets a reference to the given []string and assigns it to the RequiredAmr field.
func (o *IdPBindingRequest) SetRequiredAmr(v []string) {
	o.RequiredAmr = v
}

// GetJitPolicy returns the JitPolicy field value
func (o *IdPBindingRequest) GetJitPolicy() IdPBindingRequestJitPolicy {
	if o == nil {
		var ret IdPBindingRequestJitPolicy
		return ret
	}

	return o.JitPolicy
}

// GetJitPolicyOk returns a tuple with the JitPolicy field value
// and a boolean to check if the value has been set.
func (o *IdPBindingRequest) GetJitPolicyOk() (*IdPBindingRequestJitPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JitPolicy, true
}

// SetJitPolicy sets field value
func (o *IdPBindingRequest) SetJitPolicy(v IdPBindingRequestJitPolicy) {
	o.JitPolicy = v
}

func (o IdPBindingRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdPBindingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain_id"] = o.DomainId
	toSerialize["issuer"] = o.Issuer
	toSerialize["client_id"] = o.ClientId
	toSerialize["client_secret_ref"] = o.ClientSecretRef
	toSerialize["discovery_url"] = o.DiscoveryUrl
	if !IsNil(o.ClaimMappings) {
		toSerialize["claim_mappings"] = o.ClaimMappings
	}
	if !IsNil(o.RequiredAcr) {
		toSerialize["required_acr"] = o.RequiredAcr
	}
	if !IsNil(o.RequiredAmr) {
		toSerialize["required_amr"] = o.RequiredAmr
	}
	toSerialize["jit_policy"] = o.JitPolicy

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdPBindingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain_id",
		"issuer",
		"client_id",
		"client_secret_ref",
		"discovery_url",
		"jit_policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdPBindingRequest := _IdPBindingRequest{}

	err = json.Unmarshal(data, &varIdPBindingRequest)

	if err != nil {
		return err
	}

	*o = IdPBindingRequest(varIdPBindingRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain_id")
		delete(additionalProperties, "issuer")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "client_secret_ref")
		delete(additionalProperties, "discovery_url")
		delete(additionalProperties, "claim_mappings")
		delete(additionalProperties, "required_acr")
		delete(additionalProperties, "required_amr")
		delete(additionalProperties, "jit_policy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdPBindingRequest struct {
	value *IdPBindingRequest
	isSet bool
}

func (v NullableIdPBindingRequest) Get() *IdPBindingRequest {
	return v.value
}

func (v *NullableIdPBindingRequest) Set(val *IdPBindingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIdPBindingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIdPBindingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdPBindingRequest(val *IdPBindingRequest) *NullableIdPBindingRequest {
	return &NullableIdPBindingRequest{value: val, isSet: true}
}

func (v NullableIdPBindingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdPBindingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
