/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CloudCredentialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudCredentialResponse{}

// CloudCredentialResponse Metadata-only projection of a Cloud Credential. The shape is shared by `GetCloudCredential`, `ListCloudCredentials`, and `RevokeCloudCredential` so clients only need one binding.  The projection deliberately omits the KV mount, KV path, KV version, and every byte of secret material — the storage location is a storage-internal detail the operator-facing surface has no reason to expose.
type CloudCredentialResponse struct {
	// Cloud Credential identifier (UUIDv7).
	Id string `json:"id"`
	// Identifier of the owning Cloud — the residency pivot the ReBAC gate authorises against.
	CloudId string `json:"cloud_id"`
	// Human-readable Cloud Credential name.
	DisplayName string `json:"display_name"`
	// Monotonic broker-row version. Starts at 1 on issuance and increments on every rotate.
	Version int64                 `json:"version"`
	Status  CloudCredentialStatus `json:"status"`
	// Wall-clock expiry budget (UTC).
	ExpiresAt time.Time `json:"expires_at"`
	// Revocation timestamp (UTC). `null` until the credential is revoked by an operator.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Expiry-observed timestamp (UTC). `null` until the sweeper marks the credential expired.
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// Aggregate creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-modified timestamp (UTC). Bumped by every lifecycle mutator — rotate, revoke, expire.
	UpdatedAt            time.Time `json:"updated_at"`
	AdditionalProperties map[string]interface{}
}

type _CloudCredentialResponse CloudCredentialResponse

// NewCloudCredentialResponse instantiates a new CloudCredentialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudCredentialResponse(id string, cloudId string, displayName string, version int64, status CloudCredentialStatus, expiresAt time.Time, createdAt time.Time, updatedAt time.Time) *CloudCredentialResponse {
	this := CloudCredentialResponse{}
	this.Id = id
	this.CloudId = cloudId
	this.DisplayName = displayName
	this.Version = version
	this.Status = status
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCloudCredentialResponseWithDefaults instantiates a new CloudCredentialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudCredentialResponseWithDefaults() *CloudCredentialResponse {
	this := CloudCredentialResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CloudCredentialResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CloudCredentialResponse) SetId(v string) {
	o.Id = v
}

// GetCloudId returns the CloudId field value
func (o *CloudCredentialResponse) GetCloudId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CloudId
}

// GetCloudIdOk returns a tuple with the CloudId field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetCloudIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudId, true
}

// SetCloudId sets field value
func (o *CloudCredentialResponse) SetCloudId(v string) {
	o.CloudId = v
}

// GetDisplayName returns the DisplayName field value
func (o *CloudCredentialResponse) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *CloudCredentialResponse) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetVersion returns the Version field value
func (o *CloudCredentialResponse) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *CloudCredentialResponse) SetVersion(v int64) {
	o.Version = v
}

// GetStatus returns the Status field value
func (o *CloudCredentialResponse) GetStatus() CloudCredentialStatus {
	if o == nil {
		var ret CloudCredentialStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetStatusOk() (*CloudCredentialStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CloudCredentialResponse) SetStatus(v CloudCredentialStatus) {
	o.Status = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CloudCredentialResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CloudCredentialResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise.
func (o *CloudCredentialResponse) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RevokedAt) {
		return nil, false
	}
	return o.RevokedAt, true
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *CloudCredentialResponse) HasRevokedAt() bool {
	if o != nil && !IsNil(o.RevokedAt) {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given time.Time and assigns it to the RevokedAt field.
func (o *CloudCredentialResponse) SetRevokedAt(v time.Time) {
	o.RevokedAt = &v
}

// GetExpiredAt returns the ExpiredAt field value if set, zero value otherwise.
func (o *CloudCredentialResponse) GetExpiredAt() time.Time {
	if o == nil || IsNil(o.ExpiredAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiredAt
}

// GetExpiredAtOk returns a tuple with the ExpiredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetExpiredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiredAt) {
		return nil, false
	}
	return o.ExpiredAt, true
}

// HasExpiredAt returns a boolean if a field has been set.
func (o *CloudCredentialResponse) HasExpiredAt() bool {
	if o != nil && !IsNil(o.ExpiredAt) {
		return true
	}

	return false
}

// SetExpiredAt gets a reference to the given time.Time and assigns it to the ExpiredAt field.
func (o *CloudCredentialResponse) SetExpiredAt(v time.Time) {
	o.ExpiredAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CloudCredentialResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CloudCredentialResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CloudCredentialResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CloudCredentialResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CloudCredentialResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudCredentialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["cloud_id"] = o.CloudId
	toSerialize["display_name"] = o.DisplayName
	toSerialize["version"] = o.Version
	toSerialize["status"] = o.Status
	toSerialize["expires_at"] = o.ExpiresAt
	if !IsNil(o.RevokedAt) {
		toSerialize["revoked_at"] = o.RevokedAt
	}
	if !IsNil(o.ExpiredAt) {
		toSerialize["expired_at"] = o.ExpiredAt
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CloudCredentialResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"cloud_id",
		"display_name",
		"version",
		"status",
		"expires_at",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudCredentialResponse := _CloudCredentialResponse{}

	err = json.Unmarshal(data, &varCloudCredentialResponse)

	if err != nil {
		return err
	}

	*o = CloudCredentialResponse(varCloudCredentialResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "cloud_id")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "version")
		delete(additionalProperties, "status")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "revoked_at")
		delete(additionalProperties, "expired_at")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCloudCredentialResponse struct {
	value *CloudCredentialResponse
	isSet bool
}

func (v NullableCloudCredentialResponse) Get() *CloudCredentialResponse {
	return v.value
}

func (v *NullableCloudCredentialResponse) Set(val *CloudCredentialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudCredentialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudCredentialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudCredentialResponse(val *CloudCredentialResponse) *NullableCloudCredentialResponse {
	return &NullableCloudCredentialResponse{value: val, isSet: true}
}

func (v NullableCloudCredentialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudCredentialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
