/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints, and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file.  CSRF defence-in-depth: every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf_token_mismatch`, `csrf_origin_mismatch`, `csrf_origin_not_configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// checks if the SinkList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SinkList{}

// SinkList Set of sinks returned by `GET /v1/domains/{id}/sinks` (the tenant sinks one Domain declares) and by `GET /v1/sinks/built-in` (the platform's own backends), ordered by slug. Both sets are bounded — the platform ships three built-in backends, and a Domain is refused a create past its sink ceiling with `409 sink_limit_reached` — so neither is paginated.
type SinkList struct {
	// The sinks in the set.
	Items                []Sink `json:"items"`
	AdditionalProperties map[string]interface{}
}

type _SinkList SinkList

// NewSinkList instantiates a new SinkList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSinkList(items []Sink) *SinkList {
	this := SinkList{}
	this.Items = items
	return &this
}

// NewSinkListWithDefaults instantiates a new SinkList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSinkListWithDefaults() *SinkList {
	this := SinkList{}
	return &this
}

// GetItems returns the Items field value
func (o *SinkList) GetItems() []Sink {
	if o == nil {
		var ret []Sink
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SinkList) GetItemsOk() ([]Sink, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SinkList) SetItems(v []Sink) {
	o.Items = v
}

func (o SinkList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SinkList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SinkList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSinkList := _SinkList{}

	err = json.Unmarshal(data, &varSinkList)

	if err != nil {
		return err
	}

	*o = SinkList(varSinkList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSinkList struct {
	value *SinkList
	isSet bool
}

func (v NullableSinkList) Get() *SinkList {
	return v.value
}

func (v *NullableSinkList) Set(val *SinkList) {
	v.value = val
	v.isSet = true
}

func (v NullableSinkList) IsSet() bool {
	return v.isSet
}

func (v *NullableSinkList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSinkList(val *SinkList) *NullableSinkList {
	return &NullableSinkList{value: val, isSet: true}
}

func (v NullableSinkList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSinkList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
