/*
plexsphere API

HTTP contract for plexsphere's meta endpoints (health, version, self-describing OpenAPI), the identity sign-in / token endpoints , and the admin IdP-binding management surface. The specification is the single source of truth — server stubs, clients, and documentation are generated from this file .  CSRF defence-in-depth (issue #181): every state-changing cookie-authenticated `/v1/_*` request (`POST`, `PATCH`, `PUT`, `DELETE`) is required to carry both an Origin / Sec-Fetch-Site signal AND echo the `plexsphere_csrf` cookie value in the `X-Plexsphere-CSRF` header. Violations surface as `403 application/problem+json` with `code` ∈ { `csrf-token-mismatch`, `csrf-origin-mismatch`, `csrf-origin-not-configured` }. Bearer-authenticated requests (`Authorization: Bearer …`) are exempt because the bearer scheme is not auto-attached by browsers; the sign-in surface (`/v1/auth/_*`) is exempt because it cannot carry a Principal yet.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plexsphere

import (
	"encoding/json"
	"fmt"
)

// InvitationStatus Closed-set lifecycle status of an Invitation. `pending` is the initial state; `accepted`, `revoked`, and `expired` are absorbing terminal states. The four values mirror the plexsphere.invitations.status CHECK constraint and the aggregate's `Status` enum.
type InvitationStatus string

// List of InvitationStatus
const (
	INVITATIONSTATUS_PENDING                  InvitationStatus = "pending"
	INVITATIONSTATUS_ACCEPTED                 InvitationStatus = "accepted"
	INVITATIONSTATUS_REVOKED                  InvitationStatus = "revoked"
	INVITATIONSTATUS_EXPIRED                  InvitationStatus = "expired"
	INVITATIONSTATUS_UNKNOWN_DEFAULT_OPEN_API InvitationStatus = "unknown_default_open_api"
)

// All allowed values of InvitationStatus enum
var AllowedInvitationStatusEnumValues = []InvitationStatus{
	"pending",
	"accepted",
	"revoked",
	"expired",
	"unknown_default_open_api",
}

func (v *InvitationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := InvitationStatus(value)
	for _, existing := range AllowedInvitationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = INVITATIONSTATUS_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewInvitationStatusFromValue returns a pointer to a valid InvitationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewInvitationStatusFromValue(v string) (*InvitationStatus, error) {
	ev := InvitationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for InvitationStatus: valid values are %v", v, AllowedInvitationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v InvitationStatus) IsValid() bool {
	for _, existing := range AllowedInvitationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to InvitationStatus value
func (v InvitationStatus) Ptr() *InvitationStatus {
	return &v
}

type NullableInvitationStatus struct {
	value *InvitationStatus
	isSet bool
}

func (v NullableInvitationStatus) Get() *InvitationStatus {
	return v.value
}

func (v *NullableInvitationStatus) Set(val *InvitationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationStatus(val *InvitationStatus) *NullableInvitationStatus {
	return &NullableInvitationStatus{value: val, isSet: true}
}

func (v NullableInvitationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
